export const academicPartners = [
  {
    name: "EM Normandie",
    pays: "France",
    code: "FR",
    slug: "em-normandie",
    logo: "/images/ebs-tn/EM_Normandie-Logo.png",
    desc: "Fondée en 1871, EM Normandie est une Grande École française de management, membre de la Conférence des Grandes Écoles et bénéficiant de la triple accréditation internationale EQUIS, AACSB et AMBA.",
  },
  {
    name: "Excelia",
    pays: "France",
    code: "FR",
    slug: "excelia",
    logo: "/images/partenaires-academiques/excelia.webp",
    desc: "Excelia Business School est une Grande École française reconnue pour son ouverture internationale et ses formations en management, du Bachelor au Bac+5.",
  },
  {
    name: "PSB Paris",
    pays: "France",
    code: "FR",
    slug: "psb",
    logo: "/images/partenaires-academiques/psb.webp",
    desc: "Paris School of Business est une Grande École française membre de la Conférence des Grandes Écoles et bénéficiant de la triple accréditation AACSB, EQUIS et AMBA.",
  },
  {
    name: "Éklore-ed",
    pays: "France",
    code: "FR",
    slug: "eklore",
    logo: "/images/partenaires-academiques/eklore.webp",
    desc: "EKLORE-ed, anciennement ESC Pau Business School, est une Grande École de commerce proposant des formations du Bachelor au Bac+5 dans divers domaines.",
  },
  {
    name: "Epitech",
    pays: "France",
    code: "FR",
    slug: "epitech",
    logo: "/images/partenaires-academiques/epitech.webp",
    desc: "EPITECH est une école française spécialisée dans l'informatique, reconnue pour sa pédagogie intensive fondée sur les projets et la pratique.",
  },
  {
    name: "EPSI",
    pays: "France",
    code: "FR",
    slug: "epsi",
    logo: "/images/partenaires-academiques/epsi.webp",
    desc: "Créée en 1961, EPSI forme des professionnels du numérique. Sa pédagogie Learning by Doing privilégie les projets et la mise en pratique.",
  },
  {
    name: "IDRAC",
    pays: "France",
    code: "FR",
    slug: "idrac",
    logo: "/images/partenaires-academiques/idrac.webp",
    desc: "Fondée en 1965, IDRAC Business School propose des formations en commerce, management, marketing, stratégie, international, innovation et supply chain.",
  },
  {
    name: "IFAG",
    pays: "France",
    code: "FR",
    slug: "ifag",
    logo: "/images/partenaires-academiques/ifag.webp",
    desc: "Créée en 1968, IFAG est une école française de management spécialisée dans les domaines du commerce, des ressources humaines et de l'entrepreneuriat.",
  },
  {
    name: "Sup'de Com",
    pays: "France",
    code: "FR",
    slug: "supdecom",
    logo: "/images/partenaires-academiques/supdecom.webp",
    desc: "SUP'DE COM forme aux différents métiers de la communication : stratégie de communication, marketing digital, réseaux sociaux, création, événementiel et publicité.",
  },
  {
    name: "IGEFI",
    pays: "France",
    code: "FR",
    slug: "igefi",
    logo: "/images/partenaires-academiques/igefi.webp",
    desc: "IGEFI est une école supérieure française spécialisée dans les métiers de la finance d'entreprise, de la comptabilité, du contrôle de gestion et de l'expertise comptable.",
  },
  {
    name: "RED-SUP",
    pays: "France",
    code: "FR",
    slug: "redsup",
    logo: "/images/partenaires-academiques/redsup.webp",
    desc: "RED-SUP est un établissement français d'enseignement supérieur spécialisé dans l'informatique, les réseaux, la sécurité informatique et la cybersécurité.",
  },
  {
    name: "UQAT",
    pays: "Canada",
    code: "CA",
    slug: "uqat",
    logo: "/images/partenaires-academiques/uqat.webp",
    desc: "Membre du réseau de l'Université du Québec, l'UQAT est une université publique canadienne proposant des formations et des activités de recherche dans plusieurs domaines.",
  },
  {
    name: "Link University",
    pays: "Italie",
    code: "IT",
    slug: "link-university",
    logo: "/images/partenaires-academiques/udl.webp",
    desc: "Située à Rome, Link University propose des programmes internationaux en management, finance, économie, innovation, technologies digitales et communication.",
  },
  {
    name: "GUtech",
    pays: "Oman",
    code: "OM",
    slug: "gutech",
    logo: "/images/partenaires-academiques/gutech.webp",
    desc: "Fondée en 2007, GUtech est une université technologique anglophone située dans le Sultanat d'Oman, développant une collaboration avec RWTH Aachen University.",
  },
] as const;

export type AcademicPartnerSlug = (typeof academicPartners)[number]["slug"];
