import type { ProgramLPData } from "@/components/program";

export const licences: Record<string, ProgramLPData> = {
  management: {
    slug: "management",
    catalogueId: "licence-management",
    type: "licence",
    title: "Licence en Management",
    tagline: "Devenez un manager augmenté par l'Intelligence Artificielle, prêt à relever les défis des entreprises de demain.",
    pitch: "La Licence en Management d'EBS forme des managers capables de piloter des équipes, des projets et des organisations dans un environnement en constante évolution. Grâce à l'intégration de l'Intelligence Artificielle, vous apprendrez à automatiser certaines tâches, à analyser les données et à renforcer votre capacité de décision afin de vous concentrer sur les activités à forte valeur ajoutée.",
    color: "#2196F3",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 15,
    publicCible: [
      "Bacheliers toutes séries (sauf Lettres et Sport)",
      "Étudiants souhaitant se réorienter vers le management",
      "Futurs entrepreneurs, chefs de projet et consultants",
    ],
    modules: [
      { title: "Fondements du management, de la gestion et des organisations", description: "Principes de management, gestion, économie, comptabilité et fonctionnement des organisations." },
      { title: "Leadership et management des équipes", description: "Leadership, management des équipes, gestion des ressources humaines et développement des compétences." },
      { title: "Gestion de projet (PMI PMBOK®, Scrum et Kanban)", description: "Méthodes de gestion de projet, management de la qualité, conduite du changement et amélioration des performances." },
      { title: "Stratégie d'entreprise et analyse de marché", description: "Management stratégique, analyse de l'environnement, développement des organisations et prise de décision." },
      { title: "Business Analytics et tableaux de bord décisionnels", description: "Analyse de données, Business Intelligence, analyses quantitatives et qualitatives et outils d'aide à la décision." },
      { title: "Management des Ressources Humaines", description: "Gestion des talents, organisation du travail, communication managériale et développement des équipes." },
      { title: "Entrepreneuriat, innovation et création d'entreprise", description: "Innovation, entrepreneuriat, business development et transformation des organisations." },
      { title: "Droit des affaires et environnement réglementaire", description: "Droit des affaires, droit des sociétés, fiscalité, conformité et environnement juridique de l'entreprise." },
      { title: "Intelligence Artificielle appliquée au management", description: "Transformation digitale, Intelligence Artificielle, systèmes d'information et outils numériques au service du management." },
      { title: "Anglais des affaires, communication professionnelle et Soft Skills", description: "Business English, communication professionnelle, développement personnel et compétences comportementales." },
      { title: "Stage professionnel et Projet de Fin d'Études (PFE)", description: "Immersion en entreprise, réalisation d'un projet concret et préparation à l'insertion professionnelle." },
    ],
    certifications: [
      { name: "Google Project Management Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Scrum Fundamentals Certified SFC™", provider: "ScrumStudy", level: "Débutant" },
      { name: "PMI Kickoff", provider: "PMI", level: "Débutant" },
      { name: "Disciplined Agile Essentials Course (PMI DA)", provider: "PMI", level: "Intermédiaire" },
      { name: "IBM SkillsBuild Business Analyst Certificate", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Agile Essentials", provider: "Google", level: "Débutant" },
      { name: "BCG : Strategy Consulting", provider: "BCG", level: "Intermédiaire", isForage: true },
      { name: "PwC : Management Consulting", provider: "PwC", level: "Intermédiaire", isForage: true },
      { name: "Lean Six Sigma White Belt Certification", provider: "ScrumStudy", level: "Débutant" },
      { name: "Google Business Intelligence Certificate", provider: "Google", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Poursuite d'études à l'international", partenaire: "France, Canada et autres pays", details: "Ce programme permet de poursuivre vos études auprès de nos universités partenaires en France, au Canada et dans d'autres pays grâce aux accords de coopération conclus par EBS." },
    ],
    debouches: [
      "Manager augmenté par l'IA (AI-Driven Manager)",
      "Chef de projet junior",
      "Manager d'équipe",
      "Business Analyst",
      "Responsable administratif",
      "Entrepreneur",
      "Chargé de développement commercial",
      "Responsable des opérations",
    ],
  },

  marketing: {
    slug: "marketing",
    catalogueId: "licence-marketing",
    type: "licence",
    title: "Licence en Marketing",
    tagline: "Alliez vision stratégique, maîtrise du digital et intelligence artificielle pour relever les défis du marketing de demain.",
    pitch: "La Licence en Marketing d'EBS est l'une des formations les plus complètes en marketing en Tunisie. Elle associe les fondamentaux du marketing aux compétences les plus recherchées en marketing digital, data, CRM, IA générative et automatisation. Vous développerez une vision stratégique du marketing tout en apprenant à exploiter les technologies d'intelligence artificielle pour optimiser les performances et devenir un AI-Driven Marketer, capable d'allier créativité, analyse et puissance des algorithmes.",
    color: "#E91E8C",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 24,
    publicCible: [
      "Bacheliers toutes séries (sauf Lettres et Sport).",
      "Passionnés par le marketing, la communication, le digital, les réseaux sociaux et les nouvelles technologies.",
      "Futurs responsables marketing, chefs de produit, spécialistes du marketing digital, chargés de communication ou entrepreneurs.",
    ],
    modules: [
      { title: "Fondements du marketing et comportement du consommateur", description: "Principes du marketing, comportement du consommateur, études de marché et environnement de l'entreprise." },
      { title: "Marketing digital stratégique et e-commerce", description: "Marketing stratégique, marketing digital, e-commerce et transformation digitale des entreprises." },
      { title: "SEO / SEA et référencement (Google Ads)", description: "Référencement naturel et payant, acquisition de trafic et optimisation de la visibilité en ligne." },
      { title: "Social Media Marketing et Community Management", description: "Communication digitale, réseaux sociaux, gestion de communautés et réputation numérique." },
      { title: "Google Analytics 4 – Analyse des performances web", description: "Analyse des données marketing, web analytics, tableaux de bord et aide à la décision." },
      { title: "Content Marketing, Copywriting et Storytelling", description: "Création de contenus, communication de marque, storytelling et stratégie éditoriale." },
      { title: "CRM, gestion de la relation client et Marketing Automation (HubSpot)", description: "Gestion de la relation client, fidélisation, CRM, email marketing et automatisation des campagnes." },
      { title: "LinkedIn Marketing et Social Selling B2B", description: "Marketing B2B, développement commercial, négociation et techniques de vente." },
      { title: "Intelligence Artificielle appliquée au marketing", description: "Intelligence Artificielle, data marketing, personnalisation, analyse prédictive et automatisation des actions marketing." },
      { title: "Publicité programmatique (DV360, SA360)", description: "Publicité digitale, campagnes multicanales, pilotage des investissements marketing et mesure des performances." },
      { title: "Stage professionnel et Projet de Fin d'Études (PFE)", description: "Immersion en entreprise, marketing international, Responsabilité Sociétale des Entreprises (RSE), éthique professionnelle et réalisation du Projet de Fin d'Études." },
    ],
    certifications: [
      { name: "Google Fundamentals of Digital Marketing", provider: "Google", level: "Débutant" },
      { name: "Google Analytics Certification (GA4)", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Search Certification", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Display Certification", provider: "Google", level: "Intermédiaire" },
      { name: "HubSpot Digital Marketing Certification", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Content Marketing Certification", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Inbound Marketing Certification", provider: "HubSpot", level: "Débutant" },
      { name: "SEO Essentials with Semrush (AI Optimization)", provider: "SEMrush", level: "Débutant" },
      { name: "Technical SEO and AI Search Essentials", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy Certification", provider: "LinkedIn", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Poursuite d'études à l'international", partenaire: "France, Italie, Canada et autres", details: "Ce programme permet de poursuivre vos études auprès de nos universités partenaires en France, en Italie, au Canada et dans d'autres pays grâce aux accords de coopération conclus par EBS." },
    ],
    debouches: [
      "AI-Driven Marketer",
      "Responsable Marketing",
      "Chef de Produit",
      "Chargé d'Études Marketing",
      "Responsable Communication",
      "Responsable Commercial",
      "Digital Marketing Manager",
      "Marketing Data Analyst",
      "Responsable CRM",
      "Spécialiste SEO / SEA",
      "Social Media Manager",
    ],
  },

  finance: {
    slug: "finance",
    catalogueId: "licence-finance",
    type: "licence",
    title: "Licence en Finance",
    tagline: "Maîtrisez la finance, les données et l'Intelligence Artificielle pour accompagner les décisions financières de demain.",
    pitch: "La Licence en Finance d'EBS prépare des spécialistes capables d'évoluer dans les domaines de la finance d'entreprise, de la banque, des marchés financiers et de la FinTech. Grâce aux certifications Bloomberg, à l'analyse de données et à l'Intelligence Artificielle, vous développerez des compétences techniques et analytiques particulièrement recherchées par les entreprises et les institutions financières. Au-delà de la maîtrise des outils financiers, cette licence vous apprend à interpréter les données, anticiper les risques, évaluer les opportunités d'investissement et contribuer aux décisions stratégiques des organisations. Vous évoluerez dans un environnement d'apprentissage connecté aux transformations du secteur financier, où la digitalisation, la data et l'Intelligence Artificielle redéfinissent les métiers de la finance.",
    color: "#00BCD4",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 14,
    publicCible: [
      "Bacheliers toutes séries (sauf Lettres et Sport)",
      "Futurs analystes financiers, banquiers, contrôleurs de gestion ou auditeurs",
      "Passionnés de finance, d'économie et des marchés financiers",
    ],
    modules: [
      { title: "Comptabilité générale et analytique", description: "Comptabilité financière, comptabilité de gestion et analyse des coûts." },
      { title: "Mathématiques financières, statistiques et économétrie", description: "Mathématiques, statistiques, économétrie et modélisation des données financières." },
      { title: "Analyse financière et diagnostic d'entreprise", description: "Analyse des états financiers, diagnostic de la performance et prise de décision." },
      { title: "Marchés financiers et produits d'investissement", description: "Marchés financiers, produits d'investissement et environnement bancaire." },
      { title: "Finance d'entreprise et évaluation (DCF, comparables)", description: "Finance d'entreprise, politiques financières, ingénierie financière et valorisation des entreprises." },
      { title: "Contrôle de gestion et reporting financier", description: "Pilotage de la performance, contrôle de gestion et tableaux de bord." },
      { title: "FinTech et finance numérique", description: "Transformation digitale de la finance, FinTech et nouveaux services financiers." },
      { title: "ESG, finance durable et gestion des risques", description: "Finance durable, analyse des risques, RSE et éthique des affaires." },
      { title: "Python appliqué à la finance", description: "Analyse de données financières, automatisation et Business Analytics." },
      { title: "Utilisation du Terminal Bloomberg", description: "Analyse des marchés, données financières et aide à la décision." },
      { title: "Stage professionnel et Projet de Fin d'Études (PFE)", description: "Immersion en banque, cabinet ou entreprise, réalisation du PFE et préparation à l'insertion professionnelle." },
    ],
    certifications: [
      { name: "Bloomberg Market Concepts Certificate (BMC)", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Finance Fundamentals Certificate", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg ESG Certificate", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Spreadsheet Analysis Certificate", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Google Data Analytics Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Goldman Sachs : Risk", provider: "Goldman Sachs", level: "Intermédiaire", isForage: true },
      { name: "Citi : Investment Banking", provider: "Citi", level: "Intermédiaire", isForage: true },
      { name: "JP Morgan : Investment Banking", provider: "JP Morgan", level: "Intermédiaire", isForage: true },
      { name: "IBM Finance & Accounting Essentials Badge", provider: "IBM", level: "Débutant" },
      { name: "Oliver Wyman : Financial Services & Climate", provider: "Oliver Wyman", level: "Intermédiaire", isForage: true },
    ],
    internationalPathways: [
      { programme: "Poursuite d'études à l'international", partenaire: "France, Canada et autres pays", details: "Ce programme permet de poursuivre vos études auprès de nos universités partenaires en France, au Canada et dans d'autres pays grâce aux accords de coopération conclus par EBS." },
    ],
    debouches: [
      "AI-Driven Financial Consultant",
      "Analyste financier",
      "Contrôleur de gestion",
      "Chargé de clientèle bancaire",
      "Auditeur junior",
      "Conseiller en gestion de patrimoine",
      "Responsable comptable",
      "Analyste crédit",
    ],
  },


  "informatique-ia": {
    slug: "informatique-ia",
    catalogueId: "licence-informatique-ia",
    type: "licence",
    title: "Licence Informatique — Option IA",
    tagline: "Concevez les logiciels intelligents qui transformeront les entreprises de demain.",
    pitch: "La Licence Informatique – Génie Logiciel et Systèmes d'Information (option Intelligence Artificielle) d'EBS prépare des professionnels capables de concevoir, développer et déployer des applications logicielles intégrant les technologies de l'Intelligence Artificielle. Le programme associe les fondamentaux du génie logiciel, des systèmes d'information, des bases de données et du Cloud avec une spécialisation progressive en Intelligence Artificielle afin de répondre aux besoins croissants des entreprises en compétences numériques. Cette formation intègre également des certifications internationales reconnues.",
    color: "#9C27B0",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 18,
    publicCible: [
      "Bacheliers toutes séries (sauf Lettres et Sport)",
      "Passionnés de programmation, de développement logiciel et d'Intelligence Artificielle",
      "Futurs développeurs logiciels, ingénieurs en Intelligence Artificielle, développeurs d'applications ou spécialistes des systèmes d'information",
    ],
    modules: [
      { title: "Mathématiques appliquées, algorithmique et programmation", description: "Algèbre, analyse, algorithmique, structures de données, programmation Python et Java." },
      { title: "Systèmes d'exploitation, architecture des ordinateurs et réseaux", description: "Architecture des ordinateurs, systèmes d'exploitation, réseaux informatiques et services réseau." },
      { title: "Bases de données et systèmes d'information", description: "Bases de données relationnelles (SQL), ingénierie et administration des bases de données, systèmes d'information." },
      { title: "Génie logiciel, programmation orientée objet et méthodes agiles", description: "Ingénierie des exigences, UML, programmation orientée objet, développement logiciel et méthodes agiles." },
      { title: "Développement Web, Mobile et Cloud", description: "Technologies Web, développement mobile, Cloud Computing, DevOps et services Web." },
      { title: "Intelligence Artificielle et Machine Learning", description: "Fondements de l'Intelligence Artificielle, Machine Learning, Deep Learning et préparation aux certifications Microsoft AI et AWS AI." },
      { title: "Data Engineering, Big Data et MLOps", description: "Ingénierie des données, Big Data, MLOps et déploiement de modèles d'Intelligence Artificielle." },
      { title: "Intelligence Artificielle générative et applications avancées", description: "Traitement automatique du langage (NLP), Large Language Models (LLM), systèmes de recommandation, IA générative, agents IA et Computer Vision." },
      { title: "Qualité logicielle, sécurité et tests", description: "Tests logiciels, qualité logicielle, sécurité des applications et protection des systèmes d'information." },
      { title: "Communication professionnelle, Soft Skills et entrepreneuriat", description: "Communication en français et en anglais, compétences numériques, développement personnel, entrepreneuriat et préparation à la vie professionnelle." },
      { title: "Projet de Fin d'Études (PFE)", description: "Projet de fin d'études réalisé en entreprise sur une problématique réelle de développement logiciel ou d'Intelligence Artificielle. (Semestre 6)" },
    ],
    certifications: [
      { name: "CS50's Introduction to AI with Python", provider: "Harvard", level: "Intermédiaire" },
      { name: "Machine Learning Specialization", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "Deep Learning Specialization", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "TensorFlow Developer Professional Certificate", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
      { name: "AI Agents in your Workflows", provider: "Databricks", level: "Intermédiaire" },
      { name: "IBM: Applied Data Science", provider: "IBM", level: "Avancé" },
      { name: "Data Science with Python", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Advanced Data Analytics Certificate", provider: "Google", level: "Avancé" },
      { name: "Google Cloud: Professional Data Engineer", provider: "Google", level: "Avancé" },
    ],
    internationalPathways: [
      { programme: "Poursuite d'études à l'international", partenaire: "France, Canada et autres pays", details: "Ce programme permet de poursuivre vos études auprès de nos universités partenaires en France, au Canada et dans d'autres pays grâce aux accords de coopération conclus par EBS." },
    ],
    debouches: [
      "Développeur logiciel / applicatif",
      "Développeur Web et Mobile",
      "Développeur en Intelligence Artificielle",
      "Gestionnaire de bases de données",
      "Intégrateur de systèmes et solutions informatiques",
      "Testeur logiciel / Assurance Qualité (QA)",
      "Data Engineer Junior",
      "Assistant Machine Learning Engineer",
    ],
  },

  cybersecurite: {
    slug: "cybersecurite",
    catalogueId: "licence-cybersecurite",
    type: "licence",
    title: "Licence Informatique — Option Cybersécurité",
    tagline: "Développez des logiciels sécurisés et protégez les systèmes d'information de demain.",
    pitch: "La Licence Informatique – Génie Logiciel et Systèmes d'Information (option Cybersécurité) d'EBS prépare des professionnels capables de concevoir, développer et sécuriser des applications logicielles ainsi que des systèmes d'information. Le programme associe les fondamentaux du génie logiciel, des systèmes d'information, des bases de données et du Cloud avec une spécialisation progressive en cybersécurité afin de répondre aux besoins croissants des entreprises en sécurité numérique. Cette formation intègre également des certifications internationales reconnues.",
    color: "#FF9800",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 11,
    publicCible: [
      "Bacheliers toutes séries (sauf Lettres et Sport)",
      "Passionnés de programmation, de génie logiciel, de réseaux et de cybersécurité",
      "Futurs développeurs logiciels, spécialistes de la cybersécurité, administrateurs systèmes ou intégrateurs de solutions informatiques",
    ],
    modules: [
      { title: "Mathématiques appliquées, algorithmique et programmation", description: "Algèbre, analyse, algorithmique, structures de données, programmation Python et Java." },
      { title: "Systèmes d'exploitation, architecture des ordinateurs et réseaux", description: "Architecture des ordinateurs, systèmes d'exploitation, réseaux informatiques et services réseau." },
      { title: "Bases de données et systèmes d'information", description: "Bases de données relationnelles (SQL), ingénierie et administration des bases de données, systèmes d'information." },
      { title: "Génie logiciel, programmation orientée objet et méthodes agiles", description: "Ingénierie des exigences, UML, programmation orientée objet, développement logiciel et méthodes agiles." },
      { title: "Développement Web, Mobile et Cloud", description: "Technologies Web, développement mobile, Cloud Computing, DevOps et services Web." },
      { title: "Cybersécurité des systèmes d'information", description: "Sécurité des applications, sécurité des systèmes d'information, protection des réseaux et gestion des vulnérabilités." },
      { title: "Ethical Hacking, sécurité Cloud et DevSecOps", description: "Tests d'intrusion, sécurité Cloud, DevSecOps, bonnes pratiques de développement sécurisé et gestion des risques cyber." },
      { title: "Investigation numérique et opérations de sécurité", description: "Réponse aux incidents, Digital Forensics, supervision des systèmes, analyse des journaux et centres opérationnels de sécurité (SOC)." },
      { title: "Intelligence Artificielle appliquée à la cybersécurité", description: "Intelligence Artificielle, automatisation de la détection des menaces et utilisation de l'IA au service de la cybersécurité." },
      { title: "Communication professionnelle, Soft Skills et entrepreneuriat", description: "Communication en français et en anglais, compétences numériques, développement personnel, entrepreneuriat et préparation à la vie professionnelle." },
      { title: "Projet de Fin d'Études (PFE)", description: "Projet de fin d'études réalisé en entreprise sur une problématique réelle de développement logiciel et de cybersécurité. (Semestre 6)" },
    ],
    certifications: [
      { name: "Google Cybersecurity Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "CS50's Introduction to Cybersecurity", provider: "Harvard", level: "Débutant" },
      { name: "Ethical Hacker", provider: "Cisco NetAcad", level: "Intermédiaire" },
      { name: "Cyber Threat Management", provider: "Cisco NetAcad", level: "Avancé" },
      { name: "FCF — Fortinet Certified Fundamentals (Cybersecurity)", provider: "Fortinet", level: "Débutant" },
      { name: "FCA — Fortinet Certified Associate (Cybersecurity)", provider: "Fortinet", level: "Intermédiaire" },
      { name: "Fortinet NSE 1–4", provider: "Fortinet", level: "Avancé" },
      { name: "Mastercard : Cybersecurity", provider: "Mastercard", level: "Intermédiaire", isForage: true },
      { name: "PwC : Cyber Security Consulting", provider: "PwC", level: "Intermédiaire", isForage: true },
      { name: "EY : Technology Risk", provider: "EY", level: "Intermédiaire", isForage: true },
    ],
    internationalPathways: [
      { programme: "Poursuite d'études à l'international", partenaire: "France, Canada et autres pays", details: "Ce programme permet de poursuivre vos études auprès de nos universités partenaires en France, au Canada et dans d'autres pays grâce aux accords de coopération conclus par EBS." },
    ],
    debouches: [
      "Développeur logiciel / applicatif",
      "Gestionnaire de bases de données",
      "Testeur logiciel / Assurance Qualité (QA)",
      "Intégrateur de systèmes et solutions informatiques",
      "Technicien support informatique (niveau 1)",
      "Analyste cybersécurité junior",
      "Administrateur sécurité des systèmes",
      "Consultant cybersécurité junior",
    ],
  },
};
