import type { ProgramLPData } from "@/components/program";

const masterStaticContent: Record<string, Partial<ProgramLPData>> = {
  crm: {
    generalPresentation: {
      diplomaTitle: "Master Professionnel en CRM & Transformation Digitale",
      diploma: "Master habilité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique",
      duration: "2 années universitaires (4 semestres – 120 crédits).",
      organisation: "Formation professionnalisante articulée autour de cours, études de cas, projets, certifications, stage de longue durée et mémoire (PFE) projet de fin d'études.",
      paragraphs: [
        "Le Master CRM & Transformation Digitale d'ESPIMA Business School forme des spécialistes capables de concevoir, piloter et mettre en œuvre des stratégies de gestion de la relation client et de transformation digitale au service de la performance des organisations.",
        "Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du CRM, du marketing relationnel, de la transformation digitale, de la Business Intelligence et de l'analyse des données aux technologies les plus récentes, notamment l'Intelligence Artificielle, les plateformes CRM, l'automatisation des processus, les outils de Data Analytics et les solutions numériques utilisées par les entreprises.",
        "Cette approche permet aux étudiants de développer une double expertise, managériale et technologique, afin d'accompagner les entreprises dans l'amélioration de l'expérience client, l'optimisation des processus commerciaux, la transformation digitale et la création de valeur dans un environnement économique en constante évolution.",
      ],
    },
    objectivesIntro: "Le Master poursuit plusieurs objectifs complémentaires :",
    publicCibleIntro: "Le Master s'adresse :",
    publicCibleWording: ["aux titulaires d'une Licence en Marketing ou en Management ;", "aux titulaires d'une Licence dans des disciplines en lien avec le domaine du parcours souhaitant se spécialiser en CRM, gestion de la relation client et transformation digitale ;", "aux professionnels souhaitant développer ou actualiser leurs compétences en CRM, marketing automation, Business Intelligence, Intelligence Artificielle et transformation digitale des organisations."],
    objectives: ["maîtriser les stratégies de gestion de la relation client (CRM) et les leviers de fidélisation ;", "concevoir et piloter des projets de transformation digitale adaptés aux besoins des organisations;", "développer une expertise en analyse des données clients, Business Intelligence et aide à la décision;", "exploiter les plateformes CRM, les outils d'automatisation marketing et les technologies numériques utilisées par les entreprises ;", "utiliser l'Intelligence Artificielle pour améliorer la connaissance client, personnaliser les parcours et optimiser les performances commerciales ;", "maîtriser les processus de marketing automation, de gestion omnicanale et de transformation des organisations ;", "développer une vision stratégique de l'expérience client, de l'innovation digitale et de la création de valeur ;", "préparer les étudiants aux certifications professionnelles internationales les plus recherchées dans les domaines du CRM, de la Data, de l'IA et de la transformation digitale ;", "favoriser l'insertion professionnelle grâce à une pédagogie orientée projets, un stage de longue durée et une forte proximité avec les entreprises."],
    competencies: [{ title: "CRM & Expérience Client", items: ["Concevoir et déployer une stratégie de gestion de la relation client (CRM).", "Optimiser les parcours clients et les actions de fidélisation.", "Améliorer l'expérience client sur les différents canaux de communication.", "Piloter la performance de la relation client grâce aux indicateurs de suivi."] }, { title: "Transformation Digitale", items: ["Concevoir et piloter des projets de transformation digitale.", "Accompagner les organisations dans leur transition numérique.", "Déployer des solutions digitales adaptées aux enjeux métiers.", "Conduire le changement et favoriser l'innovation au sein des organisations."] }, { title: "Data Analytics & Business Intelligence", items: ["Collecter, analyser et exploiter les données clients.", "Concevoir des tableaux de bord décisionnels.", "Utiliser les outils de Data Analytics et de Business Intelligence.", "Transformer les données en informations utiles à la prise de décision."] }, { title: "Intelligence Artificielle appliquée au CRM", items: ["Exploiter l'Intelligence Artificielle pour personnaliser la relation client.", "Automatiser certaines actions marketing et commerciales.", "Utiliser les outils d'IA générative dans les projets CRM et de transformation digitale.", "Intégrer les technologies d'automatisation et les agents IA dans les processus de l'entreprise."] }],
    competenciesIntro: "Au terme de la formation, les diplômés seront capables de :",
    distinctiveIntro: "Le Master CRM & Transformation Digitale d’ESPIMA Business School se distingue par :",
    moduleIntro: "Le programme est structuré autour de plusieurs modules complémentaires couvrant les différents domaines du CRM, de la transformation digitale, de la Business Intelligence et de l'IA.",
    certificationDescription: "Le Master CRM & Transformation Digitale intègre un parcours comprenant plusieurs certifications professionnelles internationales, conçu pour compléter les enseignements académiques et renforcer les compétences directement applicables aux métiers du CRM, de la transformation digitale, du marketing automation, de la Business Intelligence et de l'Intelligence Artificielle. Les certifications évoluent régulièrement afin d'intégrer les nouvelles technologies et les attentes des entreprises.",
    certificationSections: [
      { title: "CRM, Marketing Automation & Outils Professionnels", items: ["Développer une maîtrise des principales plateformes CRM, des outils d'automatisation marketing et des solutions utilisées dans les métiers de la relation client grâce à des certifications telles que HubSpot Revenue Operations, HubSpot Sales Hub Software, HubSpot Service Hub Software, HubSpot Content Hub for Marketers et HubSpot Inbound Sales."] },
      { title: "Data Analytics, Business Intelligence & Transformation Digitale", items: ["Développer des compétences en analyse des données, Business Intelligence et pilotage de la transformation digitale grâce à des certifications telles que Google Business Intelligence Certificate, Google Data Analytics Certificate, Google Advanced Data Analytics Certificate, Digital Transformation (BCG) et Obtenir des données dans Power BI."] },
      { title: "Intelligence Artificielle appliquée au CRM", items: ["Exploiter l'Intelligence Artificielle pour automatiser les processus, personnaliser la relation client et améliorer la prise de décision grâce à des certifications telles que n8n Automation – Level One, watsonx Orchestrate, Transformer votre entreprise avec l'IA, Clustering Clients avec KMeans et Bring AI to Your Data."] },
      { title: "Culture IA", items: ["Acquérir une compréhension des fondamentaux de l'Intelligence Artificielle générative, des agents IA et de leurs applications dans les métiers du CRM et de la transformation digitale à travers des certifications telles que Agentic AI in Practice, Foundations & Applications of Generative AI, Generative AI Fundamentals, Déverrouiller le potentiel commercial — Agents IA et AI for Good Specialization."] },
    ],
    iaIntro: "L'Intelligence Artificielle est intégrée progressivement dans l'ensemble du parcours afin de préparer les étudiants aux nouveaux usages du CRM, de la transformation digitale et de la gestion de la relation client.",
    iaApplicationsIntro: "Les étudiants apprennent notamment à utiliser l'IA pour :",
    iaContent: ["analyser les données clients et améliorer la prise de décision grâce à la Business Intelligence et à l'analyse prédictive ;", "personnaliser les parcours clients, optimiser l'expérience utilisateur et développer des stratégies de fidélisation intelligentes ;", "automatiser les processus commerciaux, marketing et de service client à l'aide de workflows intelligents et d'agents IA ;", "développer des solutions de CRM intelligent intégrant le Lead Scoring, la segmentation avancée, les assistants conversationnels et les recommandations automatisées."],
    iaDescription: "Les étudiants mettent en pratique ces différentes applications grâce à l'utilisation de plateformes professionnelles telles que HubSpot AI, ChatGPT, Microsoft Copilot, Google Gemini, IBM watsonx et n8n, utilisées pour développer des solutions innovantes en CRM, Business Intelligence, automatisation des processus et transformation digitale.",
    iaConclusion: "Grâce à cette approche, les étudiants développent une maîtrise des principales applications de l'Intelligence Artificielle au service de la relation client, de la performance des organisations et de la transformation digitale.",
    pedagogyIntro: "Le Master privilégie une pédagogie active et professionnalisante associant enseignements académiques, études de cas, projets collaboratifs, ateliers pratiques, certifications internationales et immersion en entreprise.",
    pedagogy: ["Les étudiants travaillent sur des problématiques concrètes inspirées des entreprises et utilisent des plateformes professionnelles afin de développer des compétences immédiatement opérationnelles en CRM, Data Analytics, Business Intelligence, Intelligence Artificielle et transformation digitale."],
    pedagogyConclusion: "Cette approche favorise l'acquisition progressive de compétences techniques, managériales et comportementales répondant aux attentes du marché de l'emploi.",
    stageMemoire: ["Stage professionnel : une immersion de longue durée au sein d’entreprises partenaires pour mettre en pratique les compétences acquises.", "Mémoire ou projet de fin d’études : réalisation d’un projet basé sur une problématique réelle liée au CRM, à la transformation digitale, à la Business Intelligence ou à l’Intelligence Artificielle.", "Soutenance : présentation devant un jury d’enseignants et de professionnels, permettant de valoriser les capacités d’analyse, d’innovation et de conduite de projet."],
    professionalOutcomesIntro: "Le Master CRM & Transformation Digitale prépare les étudiants aux métiers de la relation client, du digital, du marketing, de la data et de la performance commerciale. Les diplômés peuvent notamment exercer les fonctions suivantes :",
    professionalOutcomesConclusion: "Avec l’expérience, les diplômés peuvent évoluer vers des postes de direction dans les domaines du CRM, de la transformation digitale, de l’expérience client, du marketing ou de la performance commerciale.",
    internationalIntro: "Après la validation du Master 1 à ESPIMA Business School, les étudiants peuvent poursuivre leurs études auprès de nos universités partenaires en France, en Italie ou au Canada, sous réserve des conditions d'admission propres à chaque établissement.",
    finalAdvantagesIntro: "Le Master CRM & Transformation Digitale d'ESPIMA Business School offre une formation professionnalisante qui associe les fondamentaux du CRM, de la transformation digitale, de la Business Intelligence et de l'Intelligence Artificielle afin de préparer les étudiants aux nouveaux métiers de la relation client et de la performance des organisations. Le programme se distingue notamment par :",
    finalAdvantages: ["un diplôme habilité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique ;", "une pédagogie orientée vers les projets, les études de cas et les besoins des entreprises ;", "l'intégration de l'Intelligence Artificielle dans l'ensemble du parcours ;", "des plateformes professionnelles telles que HubSpot CRM, Power BI, Google Analytics, n8n et IBM watsonx ;", "un parcours comprenant des certifications professionnelles internationales reconnues ;", "un stage obligatoire de longue durée favorisant une insertion professionnelle rapide ;", "des partenariats académiques permettant une poursuite d'études en France, en Italie et au Canada ;", "des débouchés dans les métiers du CRM, de l'expérience client, de la Business Intelligence, de la transformation digitale et du management de projets."],
  },
  "marketing-digital-ia": {
    generalPresentation: { diplomaTitle: "Master Professionnel en Marketing Digital & Intelligence Artificielle", diploma: "Master habilité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique", duration: "2 années universitaires (4 semestres – 120 crédits).", organisation: "Formation professionnalisante articulée autour de cours, études de cas, projets, certifications, stage de longue durée et mémoire (PFE) projet de fin d'études.", paragraphs: ["Le Master Marketing Digital & Intelligence Artificielle d'ESPIMA Business School forme des cadres capables de concevoir, piloter et optimiser des stratégies marketing dans un environnement où le digital, les données et l'Intelligence Artificielle occupent une place centrale.", "Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du marketing stratégique, du marketing digital, du e-business, de la communication numérique, du CRM et de l'analyse des données avec les technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, le Marketing Automation et les outils numériques utilisés par les entreprises.", "Cette approche permet aux étudiants de développer une double expertise, stratégique et opérationnelle, afin d'accompagner efficacement la transformation digitale des organisations et d'améliorer leur performance marketing."] },
    publicCibleIntro: "Le Master s'adresse :", competenciesIntro: "Au terme de la formation, les diplômés seront capables de maîtriser les compétences essentielles suivantes :", distinctiveIntro: "Programme habilité par l’État tunisien", moduleIntro: "Le programme est structuré autour de plusieurs modules complémentaires couvrant les différents domaines du marketing digital, de la communication numérique, de la gestion de la relation client, de la Business Intelligence et de l’Intelligence Artificielle.",
    publicCibleWording: ["aux titulaires d'une Licence en Marketing ou en Management ;", "aux titulaires d'une Licence dans des disciplines en lien avec le domaine souhaitant se spécialiser en marketing digital et en Intelligence Artificielle appliquée au marketing.", "aux professionnels souhaitant développer ou actualiser leurs compétences en marketing digital, transformation digitale et Intelligence Artificielle."],
    objectives: ["Élaborer et piloter une stratégie de marketing digital adaptée aux objectifs de l'entreprise ;", "Développer des stratégies d'acquisition, de fidélisation et de gestion de la relation client dans un environnement omnicanal ;", "Concevoir et mettre en œuvre des dispositifs de communication digitale performants ;", "Exploiter les données marketing afin de mesurer la performance et d'améliorer la prise de décision ;", "Intégrer les outils du e-business, du CRM, du marketing automation et de la Business Intelligence dans les projets marketing ;", "Utiliser l'Intelligence Artificielle pour optimiser la création de contenus, l'analyse des données, la personnalisation des campagnes et l'automatisation des processus marketing ;", "Piloter des projets de transformation digitale et accompagner les entreprises dans leur évolution numérique ;", "Développer une démarche d'innovation, de veille stratégique et d'amélioration continue adaptée aux nouveaux enjeux du marketing."],
    distinctiveAdvantages: ["Intelligence Artificielle intégrée dans l'ensemble du parcours.", "Plus de 20 certifications professionnelles internationales incluses selon le programme.", "Enseignements combinant théorie, études de cas, projets et applications concrètes.", "Utilisation des principaux outils et plateformes employés par les entreprises.", "Stage professionnel de longue durée et accompagnement vers l'emploi.", "Possibilités de poursuite d'études auprès des universités partenaires d'ESPIMA.", "Pédagogie orientée vers l'innovation, la professionnalisation et les besoins du marché."],
    certificationDescription: "Le Master intègre un parcours comprenant une vingtaine de certifications professionnelles internationales, conçu pour compléter les enseignements académiques et renforcer les compétences directement applicables aux métiers du marketing digital et de l'Intelligence Artificielle.",
    iaIntro: "À ESPIMA Business School, l'Intelligence Artificielle n'est pas une spécialisation isolée : elle constitue un socle commun intégré dans l'ensemble des Masters.", iaApplicationsIntro: "Les étudiants apprennent notamment à :", iaContent: ["exploiter l'IA générative dans les activités marketing ;", "créer des contenus assistés par l'IA ;", "concevoir des prompts efficaces ;", "automatiser des campagnes marketing ;", "analyser les données grâce à l'IA ;", "personnaliser l'expérience client ;", "améliorer les performances des campagnes digitales ;", "intégrer les assistants IA dans les processus marketing."], iaDescription: "Dans le Master Marketing Digital & Intelligence Artificielle, elle est utilisée comme un véritable levier de création de valeur pour les entreprises.", iaConclusion: "L'objectif n'est pas de former des spécialistes de l'Intelligence Artificielle, mais des professionnels du marketing capables d'utiliser efficacement l'IA dans leur métier.",
    pedagogyIntro: "Le Master privilégie une pédagogie professionnalisante reposant sur l’articulation entre enseignements académiques, mises en situation, projets et expériences en entreprise.", pedagogy: ["Les étudiants développent leurs compétences à travers des études de cas réels ;", "des projets individuels et collectifs ;", "des ateliers pratiques ;", "des simulations professionnelles ;", "des conférences animées par des experts ;", "l'utilisation des outils numériques utilisés par les entreprises ;", "la préparation aux certifications internationales."], pedagogyConclusion: "Cette approche favorise le développement de compétences directement transférables dans le monde professionnel.", stageIntro: "Le quatrième semestre est consacré à une immersion professionnelle obligatoire, permettant aux étudiants de mettre en pratique les compétences acquises tout au long du parcours.", stageMemoire: ["un stage de longue durée ;", "la réalisation d’un mémoire professionnel ;", "la réalisation d’un projet de consulting pour une entreprise."], professionalOutcomesIntro: "Le Master prépare aux fonctions suivantes :", professionalOutcomesConclusion: "Selon leur expérience professionnelle, les diplômés pourront également évoluer vers des fonctions de direction marketing ou de pilotage de la transformation digitale.", internationalIntro: "Après la validation du Master 1 à ESPIMA Business School, les étudiants peuvent poursuivre leurs études auprès de nos universités et Grandes Écoles partenaires en France, en Italie ou au Canada, conformément aux accords de partenariat et aux conditions d'admission propres à chaque établissement.", finalAdvantagesIntro: "Le Master Marketing Digital & Intelligence Artificielle d'ESPIMA Business School se distingue par :", finalAdvantages: ["un Master accrédité par l'État tunisien ;", "un programme alliant exigences académiques et compétences recherchées par les entreprises ;", "l'intégration de l'Intelligence Artificielle dans l'ensemble des enseignements ;", "un parcours de plus de 20 certifications professionnelles internationales selon le programme ;", "la maîtrise des outils et plateformes de référence du marketing digital ;", "une pédagogie fondée sur des projets, des études de cas et des mises en situation professionnelles ;", "un stage professionnel de longue durée favorisant l'insertion professionnelle ;", "des opportunités de poursuite d'études à l'international auprès des universités partenaires d'EBS ;", "Une organisation favorisant un accompagnement personnalisé"],
  },
  startups: {
    publicCibleWording: ["Titulaires d'une Licence en Management.", "Titulaires d'une Licence en Marketing.", "Titulaires d'une Licence en Finance.", "Titulaires d'une Licence en Économie.", "Titulaires d'une formation universitaire Bac+3 ou plus à dominante technique, dont la candidature est étudiée au cas par cas en fonction du parcours académique et professionnel."],
    objectives: ["Définir, planifier, piloter et évaluer des projets selon les meilleures pratiques internationales du management de projet.", "Maîtriser les méthodes Agiles, le Lean Management, le Design Thinking et les approches d'innovation.", "Concevoir, développer et accompagner la création de startups et de nouveaux modèles d'affaires.", "Utiliser les outils de Business Analysis, de gestion des risques, de management de la qualité et de pilotage de la performance.", "Intégrer l'Intelligence Artificielle, l'automatisation et les technologies numériques dans la gestion et le suivi des projets.", "Développer des compétences en leadership, communication, négociation, conduite du changement et management d'équipes."],
    distinctiveAdvantages: ["Un Master accrédité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique.", "Une pédagogie professionnalisante fondée sur des projets concrets, des études de cas et des mises en situation réelles.", "L'intégration de l'Intelligence Artificielle et des outils d'automatisation dans le management de projet et l'innovation.", "Un parcours certifiant comprenant des certifications professionnelles internationales reconnues par les entreprises."],
    generalPresentation: { diplomaTitle: "Master Professionnel en Management de Projets Innovants & Startups", diploma: "Master habilité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique", duration: "2 années universitaires (4 semestres – 120 crédits).", organisation: "Formation professionnalisante articulée autour de cours, études de cas, projets, certifications, stage de longue durée et mémoire (PFE) projet de fin d'études.", paragraphs: ["Le Master Management de Projets Innovants & Startups d'ESPIMA Business School est une formation de haut niveau conçue pour préparer les futurs managers, chefs de projet, entrepreneurs et porteurs d'innovation capables de piloter des projets complexes, d'accompagner la transformation des organisations et de créer des entreprises innovantes.", "Dans un environnement marqué par l'accélération des transformations technologiques, l'Intelligence Artificielle, l'économie numérique et l'innovation permanente, les organisations recherchent des profils capables de gérer efficacement les projets, de conduire le changement, de développer de nouveaux produits et services et de transformer une idée en véritable opportunité de création de valeur.", "Cette formation associe les fondamentaux du management de projet aux approches les plus récentes telles que l'Agilité, le Design Thinking, le Lean Startup, le Product Management, la Business Analysis, l'Innovation Management et l'Intelligence Artificielle appliquée au pilotage des projets.", "Le programme prépare les diplômés à évoluer aussi bien dans les grandes entreprises que dans les PME, les cabinets de conseil, les startups, les organisations internationales ou à créer et développer leur propre entreprise innovante, tout en bénéficiant des opportunités offertes par les partenariats académiques internationaux d'ESPIMA Business School."] },
    publicCibleIntro: "Le Master Management de Projets Innovants & Startups s'adresse aux étudiants souhaitant développer une expertise en management de projet, innovation, entrepreneuriat et transformation des organisations, tout en acquérant des compétences immédiatement opérationnelles recherchées par les entreprises. Cette formation est particulièrement destinée aux :", competenciesIntro: "À l'issue de la formation, les diplômés développent des compétences leur permettant de piloter des projets innovants, d'accompagner la transformation des organisations et de créer de nouvelles opportunités de développement dans des environnements en constante évolution. Ils seront notamment capables de :", distinctiveIntro: "Le Master Management de Projets Innovants & Startups d'ESPIMA Business School se distingue par une approche pédagogique innovante associant management de projet, entrepreneuriat, innovation, transformation digitale et Intelligence Artificielle afin de préparer les étudiants aux nouveaux défis des organisations.", moduleIntro: "Le programme est structuré autour de plusieurs modules complémentaires couvrant les différents domaines du management de projet, de l'innovation, de l'entrepreneuriat, de la transformation digitale et de l'Intelligence Artificielle.", certificationDescription: "Le Master Management de Projets Innovants & Startups intègre un parcours certifiant permettant aux étudiants de renforcer leurs compétences en management de projet, innovation, Intelligence Artificielle, entrepreneuriat et transformation digitale grâce à des certifications internationales reconnues par les entreprises.", iaIntro: "L'Intelligence Artificielle est intégrée progressivement dans l'ensemble du parcours afin de préparer les étudiants aux nouvelles pratiques du management de projet, de l'innovation, de l'entrepreneuriat et de la transformation des organisations.", iaApplicationsIntro: "Les étudiants apprennent notamment à utiliser l'IA pour :", iaContent: ["améliorer la planification, le suivi et le pilotage des projets grâce à l'analyse prédictive et à l'aide à la décision ;", "automatiser les tâches de gestion de projet, les workflows et les processus collaboratifs ;", "développer des assistants intelligents et des agents IA pour optimiser la productivité des équipes projet ;", "accompagner l'innovation, le développement de produits et la création de startups grâce aux technologies d'IA générative ;", "analyser les données, identifier les risques et améliorer la performance des projets grâce à la Business Intelligence et à l'Intelligence Artificielle."], iaDescription: "Les étudiants mettent en pratique ces différentes applications grâce à l'utilisation de plateformes professionnelles telles que ChatGPT, Microsoft Copilot, Google Gemini, IBM watsonx, n8n et d'autres outils d'Intelligence Artificielle utilisés pour développer des solutions innovantes en management de projet, automatisation, entrepreneuriat et transformation digitale.", iaConclusion: "Grâce à cette approche, les étudiants développent une maîtrise des principales applications de l'Intelligence Artificielle au service du management de projet, de l'innovation, de la création de startups et de la performance des organisations.", pedagogyIntro: "Le Master privilégie une pédagogie active et professionnalisante associant enseignements académiques, études de cas, projets collaboratifs, ateliers pratiques, simulations, certifications internationales et immersion progressive en entreprise.", pedagogy: ["Les étudiants travaillent sur des projets concrets inspirés des problématiques des organisations et développent des solutions innovantes en utilisant les principaux outils de management de projet, de Business Analysis, d'Intelligence Artificielle et de transformation digitale."], pedagogyConclusion: "Cette approche favorise le développement de compétences techniques, managériales et entrepreneuriales répondant aux attentes des entreprises, des cabinets de conseil, des startups et des organisations en transformation.", stageMemoire: ["Stage professionnel : une immersion de longue durée en entreprise pour mettre en pratique les compétences acquises et développer son expérience professionnelle.", "Mémoire et projet de fin d’études : réalisation d’un projet basé sur une problématique réelle liée au management de projet, à l’innovation, à la transformation digitale, à l’entrepreneuriat ou à l’IA appliquée.", "Soutenance : présentation du mémoire devant un jury d’enseignants et de professionnels, permettant de valoriser les compétences d’analyse, d’innovation et de conduite de projet."], professionalOutcomesIntro: "Le Master Management de Projets Innovants & Startups prépare les diplômés à occuper des fonctions à responsabilité dans les entreprises, les cabinets de conseil, les organisations publiques et privées, les startups ou à développer leur propre activité entrepreneuriale. Les principaux débouchés sont notamment :", professionalOutcomesConclusion: "", internationalIntro: "Après la validation du Master 1 à ESPIMA Business School, les étudiants peuvent poursuivre leurs études auprès de nos universités partenaires en France, en Italie ou au Canada, sous réserve des conditions d'admission propres à chaque établissement.", finalAdvantagesIntro: "Le Master Management de Projets Innovants & Startups d'ESPIMA Business School constitue une formation professionnalisante conçue pour répondre aux nouveaux besoins des entreprises en matière de management de projet, d'innovation et d'entrepreneuriat. Le programme se distingue par :", finalAdvantages: ["une formation habilitée par le Ministère de l'Enseignement Supérieur;", "une pédagogie active fondée sur des projets réels, des études de cas et des mises en situation professionnelles ;", "l'intégration de l'Intelligence Artificielle, de l'innovation et des technologies numériques dans l'ensemble du parcours ;", "un parcours certifiant comprenant des certifications professionnelles internationales reconnues ;", "une immersion progressive en entreprise à travers les projets, le stage et le mémoire de fin d'études ;", "une ouverture internationale grâce aux partenariats académiques d'ESPIMA Business School ;", "une préparation aux métiers du management de projet, du Product Management, de l’innovation, des startups, de la transformation digitale, du conseil et de l’entrepreneuriat."],
  },
  "ingenierie-financiere": {
    publicCibleWording: ["aux titulaires d'une Licence en Finance ou en Économie ;", "aux titulaires d'une Licence dans des disciplines en lien avec la finance, souhaitant se spécialiser en ingénierie financière, finance d'entreprise, finance de marché et gestion des risques ;", "aux professionnels souhaitant développer ou actualiser leurs compétences en ingénierie financière, analyse financière, finance quantitative, gestion des risques et nouvelles technologies appliquées à la finance."],
    objectives: ["maîtriser les techniques avancées de la finance d'entreprise et de l'ingénierie financière ;", "développer une expertise en analyse financière et en évaluation d'entreprise ;", "concevoir des montages financiers adaptés aux besoins des organisations ;", "maîtriser les marchés financiers et leurs mécanismes ;", "analyser, mesurer et piloter les risques financiers ;", "utiliser les outils numériques, les technologies financières et l'Intelligence Artificielle pour améliorer l'aide à la décision ;", "développer une vision stratégique de la création de valeur et de la performance financière ;", "préparer les étudiants aux certifications professionnelles internationales les plus recherchées par les recruteurs ;", "favoriser l'insertion professionnelle grâce à une pédagogie orientée projets, un stage obligatoire et une forte proximité avec les entreprises."],
    distinctiveAdvantages: ["un programme habilité par l’État tunisien", "une approche pédagogique orientée vers les besoins réels des entreprises et des institutions financières ;", "l'intégration de l'Intelligence Artificielle dans l'ensemble du parcours ;", "un parcours certifiant permettant d'obtenir plusieurs certifications internationales valorisées sur le marché de l'emploi ;", "des projets réels, des études de cas et des simulations professionnelles ;", "un stage obligatoire de longue durée favorisant l'insertion professionnelle ;"],
    generalPresentation: { diplomaTitle: "Master Professionnel en Ingénierie Financière", diploma: "Master accrédité par le Ministère de l'Enseignement Supérieur et de la Recherche Scientifique", duration: "2 années universitaires (4 semestres – 120 crédits).", organisation: "Formation professionnalisante articulée autour de cours, études de cas, projets, certifications, stage de longue durée et mémoire (PFE) projet de fin d'études.", paragraphs: ["Le Master Ingénierie Financière d'ESPIMA Business School forme des spécialistes capables de concevoir, analyser et piloter des solutions financières adaptées aux besoins des entreprises, des institutions financières et des marchés.", "Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux de la finance d'entreprise, de la finance de marché, de l'ingénierie financière, de l'analyse financière et de la gestion des risques aux technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, la Data Analytics, les technologies FinTech et les outils numériques utilisés par les professionnels de la finance.", "Cette approche permet aux étudiants de développer une double expertise, financière et technologique, afin d'accompagner les organisations dans leurs décisions d'investissement, de financement, de gestion des risques et de création de valeur dans un environnement économique en constante évolution."] },
    publicCibleIntro: "Le Master s'adresse :", competenciesIntro: "Au terme de la formation, les diplômés seront capables de :", distinctiveIntro: "Choisir le Master Ingénierie Financière d'ESPIMA Business School, c'est intégrer une université qui prépare les futurs experts de la finance grâce à une pédagogie professionnalisante, des partenariats internationaux et une forte proximité avec les entreprises. Le programme se distingue notamment par :", moduleIntro: "Le programme est structuré autour de cinq grands blocs de compétences regroupant les principaux modules de la formation et couvrant les différents domaines de l'ingénierie financière.", certificationDescription: "Le Master intègre un parcours comprenant une vingtaine de certifications professionnelles internationales, conçu pour compléter les enseignements académiques et renforcer les compétences directement applicables aux métiers de la banque, de la finance, de l'investissement et de l'IA.", iaIntro: "À ESPIMA Business School, l'Intelligence Artificielle n'est pas une spécialisation isolée : elle constitue un socle commun intégré à l'ensemble des Masters.", iaApplicationsIntro: "Les étudiants apprennent notamment à :", iaDescription: "Dans le Master Ingénierie Financière, l'IA est utilisée comme un véritable levier d'amélioration de l'analyse financière, de la gestion des risques, de la modélisation quantitative et de l'aide à la décision.", iaContent: ["exploiter l'Intelligence Artificielle pour analyser les données financières ;", "utiliser l'IA générative pour assister les analyses et la production de rapports financiers ;", "développer des modèles prédictifs appliqués aux marchés financiers ;", "automatiser certaines tâches d'analyse, de reporting et de contrôle ;", "utiliser les technologies de Data Analytics et de Business Intelligence pour améliorer la prise de décision ;", "exploiter les outils d'IA dans les domaines de la finance d'entreprise, de la gestion des risques et de l'investissement ;", "intégrer les nouvelles technologies financières (FinTech) dans les projets de transformation des organisations ;", "développer une approche responsable de l'utilisation de l'Intelligence Artificielle dans les métiers de la finance."], iaConclusion: "L'objectif n'est pas de former des spécialistes de l'Intelligence Artificielle, mais des professionnels de la finance capables d'utiliser efficacement les outils d'IA pour améliorer leurs analyses, leurs décisions et la performance des organisations.", pedagogyIntro: "Le Master privilégie une pédagogie professionnalisante reposant sur l'articulation entre enseignements académiques, mises en situation, projets et expériences en entreprise.", pedagogy: ["des études de cas réels inspirés des problématiques rencontrées par les entreprises et les institutions financières ;", "des projets individuels et collectifs portant sur des situations financières concrètes ;", "des ateliers pratiques d'analyse financière, de modélisation et de gestion des risques ;", "des simulations professionnelles en finance d'entreprise, finance de marché et ingénierie financière ;", "des conférences animées par des experts du secteur bancaire, financier et de l'investissement ;", "des projets de consulting permettant de répondre à des problématiques d'entreprises ;", "l'utilisation des outils numériques, des plateformes professionnelles et des technologies employées par les acteurs de la finance ;", "la préparation aux certifications professionnelles internationales intégrées au parcours."], pedagogyConclusion: "Cette approche favorise le développement de compétences directement transférables dans le monde professionnel et prépare les étudiants à évoluer dans un environnement financier en constante évolution.", stageIntro: "Le quatrième semestre est consacré à une immersion professionnelle obligatoire, permettant aux étudiants de mettre en pratique les compétences acquises tout au long du parcours. Cette immersion professionnelle comprend notamment :", stageMemoire: ["un stage obligatoire de longue durée en entreprise ;", "la réalisation d'un mémoire professionnel ;", "la conduite d'un projet appliqué répondant à une problématique réelle d'une organisation ;", "une soutenance devant un jury composé d'enseignants et, le cas échéant, de professionnels."], professionalOutcomesIntro: "Le Master Ingénierie Financière prépare les étudiants à exercer des fonctions à responsabilité dans les domaines de la banque, de la finance d'entreprise, des marchés financiers, de la gestion des risques, du conseil et de l'investissement. Les diplômés peuvent notamment évoluer vers les métiers suivants :", internationalIntro: "Après la validation du Master 1 à ESPIMA Business School, les étudiants peuvent poursuivre leurs études auprès de nos universités et Grandes Écoles partenaires en France, en Italie ou au Canada, conformément aux accords de partenariat et aux conditions d'admission propres à chaque établissement.", finalAdvantagesIntro: "Le Master Ingénierie Financière d'ESPIMA Business School se distingue par :", finalAdvantages: ["un Master habilité par l'État tunisien ;", "un programme combinant exigences académiques, expertise financière et technologies innovantes;", "l'intégration de l'Intelligence Artificielle dans l'ensemble du parcours ;", "un parcours de certifications professionnelles internationales adapté aux métiers de la finance ;", "une formation couvrant la finance d'entreprise, les marchés financiers, la gestion des risques, la finance quantitative, la Business Intelligence et la FinTech ;", "une pédagogie fondée sur les études de cas, les simulations professionnelles et les projets appliqués;", "l'utilisation d'outils et de plateformes reconnus dans le secteur financier ;", "un stage professionnel de longue durée favorisant l'insertion professionnelle ;", "des opportunités de poursuite d'études auprès des universités partenaires d'ESPIMA Business School en France, en Italie et au Canada ;", "un accompagnement personnalisé vers l'emploi et le développement de carrière."],
  },
};

export const masters: Record<string, ProgramLPData> = {
  crm: {
    ...masterStaticContent.crm,
    slug: "crm",
    catalogueId: "master-crm-revops",
    type: "master",
    title: "Master CRM Marketing & Transformation Digitale",
    tagline: "Pilotez la relation client et la transformation digitale grâce à l'Intelligence Artificielle.",
    pitch: "Le Master CRM Marketing & Transformation Digitale d'EBS prépare des spécialistes capables de concevoir des stratégies CRM performantes, d'automatiser les processus métier et d'exploiter les données clients grâce à l'Intelligence Artificielle. Le programme intègre les principaux outils du marché tels que HubSpot, n8n, IBM watsonx et Power BI.",
    presentation: "Le Master CRM & Transformation Digitale d'ESPIMA Business School forme des spécialistes capables de concevoir, piloter et mettre en œuvre des stratégies de gestion de la relation client et de transformation digitale au service de la performance des organisations. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du CRM, du marketing relationnel, de la transformation digitale, de la Business Intelligence et de l'analyse des données aux technologies les plus récentes, notamment l'Intelligence Artificielle, les plateformes CRM, l'automatisation des processus, les outils de Data Analytics et les solutions numériques utilisées par les entreprises.",
    color: "#E91E63",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 12,
    publicCible: [
      "Titulaires d'une Licence en Marketing, Management ou disciplines associées",
      "Étudiants souhaitant se spécialiser en CRM, relation client et transformation digitale",
      "Professionnels souhaitant développer ou actualiser leurs compétences en marketing automation, BI et IA",
    ],
    modules: [
      { title: "CRM stratégique, expérience client et marketing relationnel", description: "Concevoir et piloter une stratégie de gestion de la relation client afin d'améliorer l'acquisition, la fidélisation et l'expérience client." },
      { title: "CRM opérationnel, Marketing Automation et outils professionnels", description: "Déployer des solutions CRM modernes pour automatiser les processus commerciaux, marketing et de service client (HubSpot, n8n)." },
      { title: "Data Analytics, Business Intelligence et Intelligence Artificielle", description: "Exploiter les données et l'Intelligence Artificielle afin d'améliorer la prise de décision et la performance des organisations." },
      { title: "Transformation digitale, Business Analysis et management de projet", description: "Accompagner la transformation digitale des organisations et piloter des projets d'innovation." },
      { title: "RevOps, gouvernance CRM et performance commerciale", description: "Optimiser la performance commerciale grâce à une approche intégrée du CRM, des ventes et du service client." },
      { title: "Développement professionnel et parcours certifiant", description: "Développer les compétences professionnelles et préparer les certifications internationales (HubSpot, Google, Microsoft, IBM, Power BI)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire." },
    ],
    certifications: [
      { name: "HubSpot CRM Software Certification", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Hub Software", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Inbound Marketing Certification", provider: "HubSpot", level: "Avancé" },
      { name: "HubSpot Revenue Operations", provider: "HubSpot", level: "Intermédiaire" },
      { name: "n8n Automation Level 1 & 2", provider: "n8n", level: "Intermédiaire" },
      { name: "watsonx Orchestrate : Automatisation IA", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Analytics Certification (GA4)", provider: "Google", level: "Intermédiaire" },
      { name: "Google Digital Marketing & E-commerce Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "SEMrush: AI-Powered Marketer", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy Certification", provider: "LinkedIn", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "MSc Digital Strategy & Innovation", partenaire: "EM Normandie — France", details: "Innovation, transformation digitale, stratégie numérique et management de projets." },
      { programme: "MSc Digital Transformation & Consulting", partenaire: "Excelia Business School — France", details: "Transformation digitale, innovation, conseil, management des organisations." },
      { programme: "Master in Management ou MSc", partenaire: "Paris School of Business — France", details: "Transformation digitale, management, marketing, Business Intelligence et innovation." },
      { programme: "Laurea Magistrale (Advanced Global Management / Tech & Comm)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management et recherche appliquée." },
    ],
    debouches: [
      "CRM Manager",
      "Customer Experience Manager",
      "Customer Success Manager",
      "Consultant CRM / Transformation Digitale",
      "Business Analyst / CRM Analyst",
      "Marketing Automation Manager",
      "Responsable Relation Client",
      "Data & CRM Analyst",
      "Responsable de la Transformation Digitale",
      "Responsable de la Performance Commerciale",
    ],
  },

  startups: {
    ...masterStaticContent.startups,
    slug: "startups",
    catalogueId: "master-startups-entrepreneuriat",
    type: "master",
    title: "Master Management de Projets Innovants & Startups",
    tagline: "Concevez, pilotez et transformez des projets innovants en entreprises à fort potentiel.",
    pitch: "Le Master Management de Projets Innovants & Startups d'ESPIMA Business School est une formation de haut niveau conçue pour préparer les futurs managers, chefs de projet, entrepreneurs et porteurs d'innovation capables de piloter des projets complexes, d'accompagner la transformation des organisations et de créer des entreprises innovantes. Cette formation associe les fondamentaux du management de projet aux approches les plus récentes telles que l'Agilité, le Design Thinking, le Lean Startup, le Product Management, la Business Analysis, l'Innovation Management et l'Intelligence Artificielle appliquée au pilotage des projets.",
    color: "#5E35B1",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 11,
    publicCible: [
      "Titulaires d'une Licence en Management, Marketing, Finance ou Économie",
      "Titulaires d'une formation Bac+3 à dominante technique",
      "Candidats motivés par l'innovation, l'entrepreneuriat et l'Intelligence Artificielle",
    ],
    modules: [
      { title: "Management de projet, leadership et pilotage de la performance", description: "Acquérir les fondamentaux du management de projet afin de planifier, organiser, piloter et réussir des projets." },
      { title: "Innovation, entrepreneuriat et développement de Startups", description: "Concevoir, développer et accompagner des projets innovants (Design Thinking, Lean Startup)." },
      { title: "Business Analysis, Data Analytics et Intelligence Artificielle", description: "Exploiter les données, les outils d'analyse et l'IA pour améliorer la prise de décision et le pilotage de projets." },
      { title: "Transformation digitale, gestion des risques et amélioration continue", description: "Accompagner la transformation des organisations (Lean Management, Six Sigma, gestion des risques)." },
      { title: "Product Management, Agilité et outils professionnels", description: "Piloter le développement de produits innovants (Méthodes Agiles, Scrum, MS Project)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle, réalisation d'un projet de fin d'études ou d'un projet entrepreneurial." },
    ],
    certifications: [
      { name: "Google Project Management Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Disciplined Agile Essentials", provider: "PMI", level: "Intermédiaire" },
      { name: "Lean Six Sigma White Belt Certification", provider: "LSS", level: "Débutant" },
      { name: "Scrum for Operations & DevOps Fundamentals", provider: "ScrumStudy", level: "Intermédiaire" },
      { name: "Scrum with AI Certified (SAC™)", provider: "ScrumStudy", level: "Intermédiaire" },
      { name: "Agentic AI in Practice", provider: "DeepLearning.AI", level: "Avancé" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
      { name: "n8n Automation – Level One", provider: "n8n", level: "Intermédiaire" },
      { name: "Bloomberg Market Concepts", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc (Entrepreneuriat, Innovation, Management de Projet)", partenaire: "EM Normandie — France", details: "Spécialisations en entrepreneuriat, innovation et management de projet." },
      { programme: "MBA (Management, Marketing, Supply Chain, Data, IA)", partenaire: "IDRAC Business School — France", details: "MBA dans des domaines variés." },
      { programme: "Master Management / Business Unit", partenaire: "IFAG — France", details: "Management, Entrepreneuriat et Business Development." },
      { programme: "MSc Digital Transformation & Consulting", partenaire: "Excelia Business School — France", details: "Transformation digitale, Innovation, Conseil." },
      { programme: "Master in Management ou MSc", partenaire: "Paris School of Business — France", details: "Management de Projet, Innovation, Entrepreneuriat, Management Stratégique." },
      { programme: "Laurea Magistrale (Advanced Global Management)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation et management." },
    ],
    debouches: [
      "Chef de Projet (Project Manager)",
      "Product Manager / Product Owner",
      "Scrum Master / Agile Project Manager",
      "Business Analyst",
      "Consultant en Management de Projet",
      "Consultant en Transformation Digitale",
      "Responsable PMO (Project Management Office)",
      "Business Development Manager",
      "Entrepreneur / Fondateur de Startup",
      "Consultant en Organisation et Innovation",
    ],
  },

  "ingenierie-financiere": {
    ...masterStaticContent["ingenierie-financiere"],
    slug: "ingenierie-financiere",
    catalogueId: "master-ingenierie-financiere",
    type: "master",
    title: "Master Ingénierie Financière",
    tagline: "Maîtrisez les techniques de la finance moderne pour accompagner les décisions stratégiques des entreprises et des marchés.",
    pitch: "Le Master Ingénierie Financière d'ESPIMA Business School forme des spécialistes capables de concevoir, analyser et piloter des solutions financières adaptées aux besoins des entreprises, des institutions financières et des marchés. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux de la finance d'entreprise, de la finance de marché, de l'ingénierie financière, de l'analyse financière et de la gestion des risques aux technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, la Data Analytics, les technologies FinTech et les outils numériques utilisés par les professionnels de la finance.",
    color: "#00897B",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 15,
    publicCible: [
      "Titulaires d'une Licence en Finance ou en Économie",
      "Titulaires d'une Licence dans des disciplines en lien avec la finance",
      "Professionnels souhaitant développer ou actualiser leurs compétences en ingénierie financière et finance quantitative",
    ],
    modules: [
      { title: "Finance d'entreprise & Analyse financière", description: "Développer une expertise en analyse financière, en évaluation d'entreprise et en prise de décision (Diagnostic financier, évaluation d'actifs)." },
      { title: "Banque, Marchés financiers & Ingénierie financière", description: "Maîtriser les mécanismes des marchés financiers et les opérations d'ingénierie financière (Produits dérivés, structurés, M&A)." },
      { title: "Gestion des risques, Finance internationale & Réglementation", description: "Identifier, mesurer et maîtriser les différents risques financiers (Risque de marché, de taux, finance internationale)." },
      { title: "Finance quantitative, Data & Intelligence Artificielle", description: "Exploiter les données, les méthodes quantitatives et les nouvelles technologies afin d'améliorer l'analyse financière (Économétrie, IA, BI)." },
      { title: "Développement professionnel & Expérience en entreprise", description: "Préparer l'intégration dans le monde professionnel (Anglais des affaires, communication, Business Game)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire professionnel." },
    ],
    certifications: [
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Market Concepts", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Spreadsheet Analysis", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Investment Banking (JPMorgan Chase)", provider: "JPMorgan Chase", level: "Intermédiaire", isForage: true },
      { name: "Risk (Goldman Sachs)", provider: "Goldman Sachs", level: "Avancé", isForage: true },
      { name: "Environmental Social Governance (ESG)", provider: "ESG", level: "Intermédiaire" },
      { name: "Markets Quantitative Analysis (Citi)", provider: "Citi", level: "Avancé", isForage: true },
      { name: "Mathematics for Machine Learning and Data Science", provider: "DeepLearning.AI", level: "Avancé" },
      { name: "Bring AI to Your Data", provider: "IBM", level: "Intermédiaire" },
      { name: "Agentic AI in Practice", provider: "DeepLearning.AI", level: "Avancé" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc, Mastères Spécialisés", partenaire: "EM Normandie Business School — France", details: "Finance, Banque, Financial Data, Management, Innovation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Excelia Business School — France", details: "Finance, Management, Entrepreneuriat, Innovation, Digital." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Paris School of Business (PSB) — France", details: "International Finance, Financial Risk Management, Accounting." },
      { programme: "Programmes spécialisés", partenaire: "IGEFI — France", details: "Finance, comptabilité, audit, contrôle de gestion." },
      { programme: "Laurea Magistrale (Economics of Innovation / Advanced Global Management)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management." },
    ],
    debouches: [
      "Analyste financier / Ingénieur financier",
      "Analyste quantitatif (Quantitative Analyst)",
      "Analyste en banque d'investissement",
      "Gestionnaire de portefeuille / Conseiller M&A",
      "Risk Manager / Analyste des risques",
      "Responsable financier / Contrôleur financier",
      "Consultant en finance d'entreprise / Transformation financière",
      "Consultant en FinTech / Data Finance",
      "Directeur Administratif et Financier (DAF)",
      "Directeur Financier (CFO)",
    ],
  },

  "marketing-digital-ia": {
    ...masterStaticContent["marketing-digital-ia"],
    slug: "marketing-digital-ia",
    catalogueId: "master-marketing-digital-ia",
    type: "master",
    title: "Master Marketing Digital & IA",
    tagline: "Développez des stratégies marketing innovantes grâce à l'Intelligence Artificielle et aux technologies digitales.",
    pitch: "Le Master Marketing Digital & IA d'EBS prépare des spécialistes capables de concevoir, piloter et optimiser des stratégies marketing performantes en s'appuyant sur l'Intelligence Artificielle, l'analyse des données et les outils digitaux les plus avancés.",
    presentation: "Le Master Marketing Digital & Intelligence Artificielle d'ESPIMA Business School forme des cadres capables de concevoir, piloter et optimiser des stratégies marketing dans un environnement où le digital, les données et l'Intelligence Artificielle occupent une place centrale. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du marketing stratégique, du marketing digital, du e-business, de la communication numérique, du CRM et de l'analyse des données avec les technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, le Marketing Automation et les outils numériques utilisés par les entreprises. Cette approche permet aux étudiants de développer une double expertise, stratégique et opérationnelle, afin d'accompagner efficacement la transformation digitale des organisations et d'améliorer leur performance marketing.",
    color: "#E91E8C",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 11,
    publicCible: [
      "Titulaires d'une Licence en Marketing, Management ou disciplines associées",
      "Étudiants souhaitant se spécialiser en marketing digital et Intelligence Artificielle",
      "Professionnels souhaitant développer ou actualiser leurs compétences en marketing digital et transformation digitale",
    ],
    modules: [
      { title: "Marketing stratégique, comportement du consommateur et innovation digitale", description: "Acquérir les fondamentaux du marketing stratégique et comprendre les nouveaux comportements des consommateurs dans un environnement numérique." },
      { title: "Marketing digital, e-business et stratégies omnicanales", description: "Concevoir et piloter une stratégie digitale intégrant le e-business, le e-commerce et la communication omnicanale." },
      { title: "Acquisition digitale, référencement et Web Analytics", description: "Optimiser la visibilité, le trafic et la performance des actions marketing (SEO, SEA, Web Analytics)." },
      { title: "Communication digitale, Content Marketing et Social Media", description: "Créer des contenus performants et développer une communication digitale adaptée aux nouveaux usages." },
      { title: "CRM, expérience client et Marketing Automation", description: "Développer des stratégies de fidélisation et automatiser la relation client (HubSpot, n8n)." },
      { title: "Data Marketing, Business Intelligence et Intelligence Artificielle", description: "Exploiter les données et l'Intelligence Artificielle pour améliorer la performance des actions marketing (IA générative, analyse prédictive)." },
      { title: "Publicité digitale, Growth Marketing et acquisition avancée", description: "Développer la croissance des entreprises grâce aux stratégies d'acquisition digitales (Google Ads, Meta Ads)." },
      { title: "Management de projets digitaux, innovation et transformation digitale", description: "Piloter des projets digitaux et accompagner la transformation des organisations." },
      { title: "Développement professionnel et parcours certifiant", description: "Renforcer les compétences professionnelles et préparer les certifications internationales." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire." },
    ],
    certifications: [
      { name: "Google Advanced Data Analytics Certificate", provider: "Google", level: "Avancé" },
      { name: "Google Ads Search Certification", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Display Certification", provider: "Google", level: "Intermédiaire" },
      { name: "HubSpot Digital Marketing", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Automation Certification", provider: "HubSpot", level: "Avancé" },
      { name: "SEO Essentials with Semrush (AI Optimization)", provider: "SEMrush", level: "Débutant" },
      { name: "Technical SEO and AI Search Essentials", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy Certification", provider: "LinkedIn", level: "Intermédiaire" },
      { name: "Meta Blueprint - Media Planning", provider: "Meta", level: "Intermédiaire" },
      { name: "n8n Automation Level 1", provider: "n8n", level: "Intermédiaire" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc, Mastères Spécialisés", partenaire: "EM Normandie Business School — France", details: "Marketing digital, Stratégie digitale, Innovation, Data, Transformation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Excelia Business School — France", details: "Marketing, Digital, Communication, Entrepreneuriat, Innovation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Paris School of Business (PSB) — France", details: "Marketing & Data, Digital Business, Data Management." },
      { programme: "Programmes spécialisés", partenaire: "Sup' de Com — France", details: "Communication, marketing digital, stratégie de marque, publicité." },
      { programme: "Laurea Magistrale (Advanced Global Management / Tech & Comm)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management et recherche appliquée." },
    ],
    debouches: [
      "Responsable Marketing Digital / Digital Marketing Manager",
      "Responsable Acquisition / Traffic Manager",
      "Growth Marketing Manager",
      "CRM & Marketing Automation Manager",
      "Consultant en stratégie digitale / Transformation Digitale",
      "Marketing Data Analyst",
      "Social Media & Content Manager",
      "E-commerce Manager",
      "Chef de Projet Digital",
      "Expert en Intelligence Artificielle appliquée au Marketing",
    ],
  },
};
