import type { ProgramLPData } from "@/components/program";

export const masters: Record<string, ProgramLPData> = {
  crm: {
    slug: "crm",
    type: "master",
    title: "Master CRM Marketing & Transformation Digitale",
    tagline: "Pilotez la relation client et la transformation digitale grâce à l'Intelligence Artificielle.",
    pitch: "Le Master CRM & Transformation Digitale d'ESPIMA Business School forme des spécialistes capables de concevoir, piloter et mettre en œuvre des stratégies de gestion de la relation client et de transformation digitale au service de la performance des organisations. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du CRM, du marketing relationnel, de la transformation digitale, de la Business Intelligence et de l'analyse des données aux technologies les plus récentes, notamment l'Intelligence Artificielle, les plateformes CRM, l'automatisation des processus, les outils de Data Analytics et les solutions numériques utilisées par les entreprises.",
    color: "#E91E63",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 24,
    publicCible: [
      "Titulaires d'une Licence en Marketing, Management ou disciplines associées",
      "Étudiants souhaitant se spécialiser en CRM, relation client et transformation digitale",
      "Professionnels souhaitant développer ou actualiser leurs compétences en marketing automation, BI et IA",
    ],
    modules: [
      { title: "CRM stratégique, expérience client et marketing relationnel", description: "Concevoir et piloter une stratégie de gestion de la relation client afin d'améliorer l'acquisition, la fidélisation et l'expérience client." },
      { title: "CRM opérationnel, Marketing Automation et outils professionnels", description: "Déployer des solutions CRM modernes pour automatiser les processus commerciaux, marketing et de service client (HubSpot, n8n)." },
      { title: "Data Analytics, Business Intelligence et Intelligence Artificielle", description: "Exploiter les données et l'Intelligence Artificielle afin d'améliorer la prise de décision et la performance des organisations." },
      { title: "Transformation digitale, Business Analysis et management de projet", description: "Accompagner la transformation digitale des organisations et piloter des projets d'innovation." },
      { title: "RevOps, gouvernance CRM et performance commerciale", description: "Optimiser la performance commerciale grâce à une approche intégrée du CRM, des ventes et du service client." },
      { title: "Développement professionnel et parcours certifiant", description: "Développer les compétences professionnelles et préparer les certifications internationales (HubSpot, Google, Microsoft, IBM, Power BI)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire." },
    ],
    certifications: [
      { name: "HubSpot CRM Software Certification", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Hub Software", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Inbound Marketing Certification", provider: "HubSpot", level: "Avancé" },
      { name: "HubSpot Revenue Operations", provider: "HubSpot", level: "Intermédiaire" },
      { name: "n8n Automation Level 1 & 2", provider: "n8n", level: "Intermédiaire" },
      { name: "watsonx Orchestrate : Automatisation IA", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Analytics Certification (GA4)", provider: "Google", level: "Intermédiaire" },
      { name: "Google Digital Marketing & E-commerce Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "SEMrush: AI-Powered Marketer", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy Certification", provider: "LinkedIn", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "MSc Digital Strategy & Innovation", partenaire: "EM Normandie — France", details: "Innovation, transformation digitale, stratégie numérique et management de projets." },
      { programme: "MSc Digital Transformation & Consulting", partenaire: "Excelia Business School — France", details: "Transformation digitale, innovation, conseil, management des organisations." },
      { programme: "Master in Management ou MSc", partenaire: "Paris School of Business — France", details: "Transformation digitale, management, marketing, Business Intelligence et innovation." },
      { programme: "Laurea Magistrale (Advanced Global Management / Tech & Comm)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management et recherche appliquée." },
    ],
    debouches: [
      "CRM Manager",
      "Customer Experience Manager",
      "Customer Success Manager",
      "Consultant CRM / Transformation Digitale",
      "Business Analyst / CRM Analyst",
      "Marketing Automation Manager",
      "Responsable Relation Client",
      "Data & CRM Analyst",
      "Responsable de la Transformation Digitale",
      "Responsable de la Performance Commerciale",
    ],
  },

  startups: {
    slug: "startups",
    type: "master",
    title: "Master Management de Projets Innovants & Startups",
    tagline: "Concevez, pilotez et transformez des projets innovants en entreprises à fort potentiel.",
    pitch: "Le Master Management de Projets Innovants & Startups d'ESPIMA Business School est une formation de haut niveau conçue pour préparer les futurs managers, chefs de projet, entrepreneurs et porteurs d'innovation capables de piloter des projets complexes, d'accompagner la transformation des organisations et de créer des entreprises innovantes. Cette formation associe les fondamentaux du management de projet aux approches les plus récentes telles que l'Agilité, le Design Thinking, le Lean Startup, le Product Management, la Business Analysis, l'Innovation Management et l'Intelligence Artificielle appliquée au pilotage des projets.",
    color: "#5E35B1",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 22,
    publicCible: [
      "Titulaires d'une Licence en Management, Marketing, Finance ou Économie",
      "Titulaires d'une formation Bac+3 à dominante technique",
      "Candidats motivés par l'innovation, l'entrepreneuriat et l'Intelligence Artificielle",
    ],
    modules: [
      { title: "Management de projet, leadership et pilotage de la performance", description: "Acquérir les fondamentaux du management de projet afin de planifier, organiser, piloter et réussir des projets." },
      { title: "Innovation, entrepreneuriat et développement de Startups", description: "Concevoir, développer et accompagner des projets innovants (Design Thinking, Lean Startup)." },
      { title: "Business Analysis, Data Analytics et Intelligence Artificielle", description: "Exploiter les données, les outils d'analyse et l'IA pour améliorer la prise de décision et le pilotage de projets." },
      { title: "Transformation digitale, gestion des risques et amélioration continue", description: "Accompagner la transformation des organisations (Lean Management, Six Sigma, gestion des risques)." },
      { title: "Product Management, Agilité et outils professionnels", description: "Piloter le développement de produits innovants (Méthodes Agiles, Scrum, MS Project)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle, réalisation d'un projet de fin d'études ou d'un projet entrepreneurial." },
    ],
    certifications: [
      { name: "Google Project Management Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Disciplined Agile Essentials", provider: "PMI", level: "Intermédiaire" },
      { name: "Lean Six Sigma White Belt Certification", provider: "LSS", level: "Débutant" },
      { name: "Scrum for Operations & DevOps Fundamentals", provider: "ScrumStudy", level: "Intermédiaire" },
      { name: "Scrum with AI Certified (SAC™)", provider: "ScrumStudy", level: "Intermédiaire" },
      { name: "Agentic AI in Practice", provider: "DeepLearning.AI", level: "Avancé" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
      { name: "n8n Automation – Level One", provider: "n8n", level: "Intermédiaire" },
      { name: "Bloomberg Market Concepts", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc (Entrepreneuriat, Innovation, Management de Projet)", partenaire: "EM Normandie — France", details: "Spécialisations en entrepreneuriat, innovation et management de projet." },
      { programme: "MBA (Management, Marketing, Supply Chain, Data, IA)", partenaire: "IDRAC Business School — France", details: "MBA dans des domaines variés." },
      { programme: "Master Management / Business Unit", partenaire: "IFAG — France", details: "Management, Entrepreneuriat et Business Development." },
      { programme: "MSc Digital Transformation & Consulting", partenaire: "Excelia Business School — France", details: "Transformation digitale, Innovation, Conseil." },
      { programme: "Master in Management ou MSc", partenaire: "Paris School of Business — France", details: "Management de Projet, Innovation, Entrepreneuriat, Management Stratégique." },
      { programme: "Laurea Magistrale (Advanced Global Management)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation et management." },
    ],
    debouches: [
      "Chef de Projet (Project Manager)",
      "Product Manager / Product Owner",
      "Scrum Master / Agile Project Manager",
      "Business Analyst",
      "Consultant en Management de Projet",
      "Consultant en Transformation Digitale",
      "Responsable PMO (Project Management Office)",
      "Business Development Manager",
      "Entrepreneur / Fondateur de Startup",
      "Consultant en Organisation et Innovation",
    ],
  },

  "ingenierie-financiere": {
    slug: "ingenierie-financiere",
    type: "master",
    title: "Master Ingénierie Financière",
    tagline: "Maîtrisez les techniques de la finance moderne pour accompagner les décisions stratégiques des entreprises et des marchés.",
    pitch: "Le Master Ingénierie Financière d'ESPIMA Business School forme des spécialistes capables de concevoir, analyser et piloter des solutions financières adaptées aux besoins des entreprises, des institutions financières et des marchés. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux de la finance d'entreprise, de la finance de marché, de l'ingénierie financière, de l'analyse financière et de la gestion des risques aux technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, la Data Analytics, les technologies FinTech et les outils numériques utilisés par les professionnels de la finance.",
    color: "#00897B",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 20,
    publicCible: [
      "Titulaires d'une Licence en Finance ou en Économie",
      "Titulaires d'une Licence dans des disciplines en lien avec la finance",
      "Professionnels souhaitant développer ou actualiser leurs compétences en ingénierie financière et finance quantitative",
    ],
    modules: [
      { title: "Finance d'entreprise & Analyse financière", description: "Développer une expertise en analyse financière, en évaluation d'entreprise et en prise de décision (Diagnostic financier, évaluation d'actifs)." },
      { title: "Banque, Marchés financiers & Ingénierie financière", description: "Maîtriser les mécanismes des marchés financiers et les opérations d'ingénierie financière (Produits dérivés, structurés, M&A)." },
      { title: "Gestion des risques, Finance internationale & Réglementation", description: "Identifier, mesurer et maîtriser les différents risques financiers (Risque de marché, de taux, finance internationale)." },
      { title: "Finance quantitative, Data & Intelligence Artificielle", description: "Exploiter les données, les méthodes quantitatives et les nouvelles technologies afin d'améliorer l'analyse financière (Économétrie, IA, BI)." },
      { title: "Développement professionnel & Expérience en entreprise", description: "Préparer l'intégration dans le monde professionnel (Anglais des affaires, communication, Business Game)." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire professionnel." },
    ],
    certifications: [
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Market Concepts", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Spreadsheet Analysis", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Investment Banking (JPMorgan Chase)", provider: "JPMorgan Chase", level: "Intermédiaire", isForage: true },
      { name: "Risk (Goldman Sachs)", provider: "Goldman Sachs", level: "Avancé", isForage: true },
      { name: "Environmental Social Governance (ESG)", provider: "ESG", level: "Intermédiaire" },
      { name: "Markets Quantitative Analysis (Citi)", provider: "Citi", level: "Avancé", isForage: true },
      { name: "Mathematics for Machine Learning and Data Science", provider: "DeepLearning.AI", level: "Avancé" },
      { name: "Bring AI to Your Data", provider: "IBM", level: "Intermédiaire" },
      { name: "Agentic AI in Practice", provider: "DeepLearning.AI", level: "Avancé" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc, Mastères Spécialisés", partenaire: "EM Normandie Business School — France", details: "Finance, Banque, Financial Data, Management, Innovation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Excelia Business School — France", details: "Finance, Management, Entrepreneuriat, Innovation, Digital." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Paris School of Business (PSB) — France", details: "International Finance, Financial Risk Management, Accounting." },
      { programme: "Programmes spécialisés", partenaire: "IGEFI — France", details: "Finance, comptabilité, audit, contrôle de gestion." },
      { programme: "Laurea Magistrale (Economics of Innovation / Advanced Global Management)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management." },
    ],
    debouches: [
      "Analyste financier / Ingénieur financier",
      "Analyste quantitatif (Quantitative Analyst)",
      "Analyste en banque d'investissement",
      "Gestionnaire de portefeuille / Conseiller M&A",
      "Risk Manager / Analyste des risques",
      "Responsable financier / Contrôleur financier",
      "Consultant en finance d'entreprise / Transformation financière",
      "Consultant en FinTech / Data Finance",
      "Directeur Administratif et Financier (DAF)",
      "Directeur Financier (CFO)",
    ],
  },

  "marketing-digital-ia": {
    slug: "marketing-digital-ia",
    type: "master",
    title: "Master Marketing Digital & IA",
    tagline: "Développez des stratégies marketing innovantes grâce à l'Intelligence Artificielle et aux technologies digitales.",
    pitch: "Le Master Marketing Digital & Intelligence Artificielle d'ESPIMA Business School forme des cadres capables de concevoir, piloter et optimiser des stratégies marketing dans un environnement où le digital, les données et l'Intelligence Artificielle occupent une place centrale. Conforme au référentiel académique validé par le Ministère de l'Enseignement Supérieur, le programme associe les fondamentaux du marketing stratégique, du marketing digital, du e-business, de la communication numérique, du CRM et de l'analyse des données avec les technologies les plus récentes, notamment l'Intelligence Artificielle, la Business Intelligence, le Marketing Automation et les outils numériques utilisés par les entreprises.",
    color: "#E91E8C",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 23,
    publicCible: [
      "Titulaires d'une Licence en Marketing, Management ou disciplines associées",
      "Étudiants souhaitant se spécialiser en marketing digital et Intelligence Artificielle",
      "Professionnels souhaitant développer ou actualiser leurs compétences en marketing digital et transformation digitale",
    ],
    modules: [
      { title: "Marketing stratégique, comportement du consommateur et innovation digitale", description: "Acquérir les fondamentaux du marketing stratégique et comprendre les nouveaux comportements des consommateurs dans un environnement numérique." },
      { title: "Marketing digital, e-business et stratégies omnicanales", description: "Concevoir et piloter une stratégie digitale intégrant le e-business, le e-commerce et la communication omnicanale." },
      { title: "Acquisition digitale, référencement et Web Analytics", description: "Optimiser la visibilité, le trafic et la performance des actions marketing (SEO, SEA, Web Analytics)." },
      { title: "Communication digitale, Content Marketing et Social Media", description: "Créer des contenus performants et développer une communication digitale adaptée aux nouveaux usages." },
      { title: "CRM, expérience client et Marketing Automation", description: "Développer des stratégies de fidélisation et automatiser la relation client (HubSpot, n8n)." },
      { title: "Data Marketing, Business Intelligence et Intelligence Artificielle", description: "Exploiter les données et l'Intelligence Artificielle pour améliorer la performance des actions marketing (IA générative, analyse prédictive)." },
      { title: "Publicité digitale, Growth Marketing et acquisition avancée", description: "Développer la croissance des entreprises grâce aux stratégies d'acquisition digitales (Google Ads, Meta Ads)." },
      { title: "Management de projets digitaux, innovation et transformation digitale", description: "Piloter des projets digitaux et accompagner la transformation des organisations." },
      { title: "Développement professionnel et parcours certifiant", description: "Renforcer les compétences professionnelles et préparer les certifications internationales." },
      { title: "Stage professionnel, mémoire et projet de fin d'études", description: "Immersion professionnelle en entreprise, réalisation d'un projet de fin d'études et rédaction d'un mémoire." },
    ],
    certifications: [
      { name: "Google Advanced Data Analytics Certificate", provider: "Google", level: "Avancé" },
      { name: "Google Ads Search Certification", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Display Certification", provider: "Google", level: "Intermédiaire" },
      { name: "HubSpot Digital Marketing", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Automation Certification", provider: "HubSpot", level: "Avancé" },
      { name: "SEO Essentials with Semrush (AI Optimization)", provider: "SEMrush", level: "Débutant" },
      { name: "Technical SEO and AI Search Essentials", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy Certification", provider: "LinkedIn", level: "Intermédiaire" },
      { name: "Meta Blueprint - Media Planning", provider: "Meta", level: "Intermédiaire" },
      { name: "n8n Automation Level 1", provider: "n8n", level: "Intermédiaire" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
    ],
    internationalPathways: [
      { programme: "PGE, MSc, Mastères Spécialisés", partenaire: "EM Normandie Business School — France", details: "Marketing digital, Stratégie digitale, Innovation, Data, Transformation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Excelia Business School — France", details: "Marketing, Digital, Communication, Entrepreneuriat, Innovation." },
      { programme: "PGE, Masters of Science (MSc)", partenaire: "Paris School of Business (PSB) — France", details: "Marketing & Data, Digital Business, Data Management." },
      { programme: "Programmes spécialisés", partenaire: "Sup' de Com — France", details: "Communication, marketing digital, stratégie de marque, publicité." },
      { programme: "Laurea Magistrale (Advanced Global Management / Tech & Comm)", partenaire: "Link University — Italie (Rome)", details: "Programmes de Master en Italie." },
      { programme: "Maîtrise en gestion de projet / Maîtrise en gestion des organisations", partenaire: "UQAT — Canada", details: "Gestion de projet, innovation, management et recherche appliquée." },
    ],
    debouches: [
      "Responsable Marketing Digital / Digital Marketing Manager",
      "Responsable Acquisition / Traffic Manager",
      "Growth Marketing Manager",
      "CRM & Marketing Automation Manager",
      "Consultant en stratégie digitale / Transformation Digitale",
      "Marketing Data Analyst",
      "Social Media & Content Manager",
      "E-commerce Manager",
      "Chef de Projet Digital",
      "Expert en Intelligence Artificielle appliquée au Marketing",
    ],
  },
};
