"use client";

import { useLocale } from "next-intl";
import type { ReactNode, ReactElement } from "react";

// Route copy is kept here rather than in programme/domain data. Only complete UI
// phrases are translated, so proper names and factual values pass through intact.
const translations: Record<string, string> = {
  "Admission sur dossier · Étude personnalisée": "Application by review · Personalised assessment",
  "Votre admission,": "Your application,",
  "étape par étape": "step by step",
  "L'admission à EBS repose sur l'étude de votre dossier académique, de votre parcours et de votre motivation. Découvrez les différentes étapes pour rejoindre EBS.": "EBS admissions are based on a review of your academic record, background and motivation. Discover the steps to join EBS.",
  "Commencer ma pré-inscription": "Start my application",
  "Explorer les programmes": "Explore programmes",
  "Processus simplifié": "A simple process",
  "4 étapes vers votre inscription": "4 steps to enrolment",
  "Pré-inscription en ligne": "Online application",
  "Étude du dossier": "Application review",
  "Entretien de motivation": "Motivation interview",
  "Confirmation d'inscription": "Enrolment confirmation",
  "Documents requis": "Required documents",
  "Dossier d'admission": "Admissions file",
  "Voir les parcours Licence": "View Bachelor's programmes",
  "Voir les Masters": "View Master's programmes",
  "Nos formations": "Our programmes",
  "Des formations professionnalisantes, avec des diplômes agréés par l'État tunisien et plus de 150 certifications internationales reconnues.": "Career-focused programmes, with Tunisian State-approved degrees and more than 150 recognised international certifications.",
  "Parcours Général": "General pathway",
  "Parcours International": "International pathway",
  "toutes spécialités": "all specialisations",
  "Voir les parcours": "View programmes",
  "Voir les destinations": "View destinations",
  "Obtenez toutes les informations sur nos tarifs": "Get full information about our fees",
  "Notre équipe vous répond sous 24 h et vous informe sur les frais de scolarité, réductions disponibles et facilités de paiement selon le programme choisi.": "Our team replies within 24 hours with information about tuition, available discounts and payment options for your chosen programme.",
  "Calendrier": "Calendar",
  "Dates clés": "Key dates",
  "Rentrée principale": "Main intake",
  "Places disponibles": "Available places",
  "Date limite": "Deadline",
  "FAQ Admissions": "Admissions FAQ",
  "Questions fréquentes sur les admissions": "Frequently asked admissions questions",
  "Prêt(e) à rejoindre EBS ?": "Ready to join EBS?",
  "Nous contacter": "Contact us",
  "Nous sommes à votre écoute": "We are here to help",
  "Parlons de votre": "Let’s talk about your",
  "avenir": "future",
  "Envoyez-nous votre message": "Send us your message",
  "Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.": "Complete the form below and we will get back to you shortly.",
  "Actions rapides": "Quick actions",
  "Horaires d'ouverture": "Opening hours",
  "Pré-inscription": "Application",
  "Prendre rendez-vous": "Book an appointment",
  "Discuter": "Chat",
  "Collaborer": "Work with us",
  "Envoyer le message": "Send message",
  "Message envoyé !": "Message sent!",
  "Votre message...": "Your message...",
  "Choisissez un sujet": "Choose a subject",
  "Inscription / Admission": "Enrolment / Admissions",
  "Information sur un programme": "Programme information",
  "Partenariat entreprise": "Corporate partnership",
  "Une erreur est survenue. Veuillez réessayer.": "Something went wrong. Please try again.",
  "Explorez le Campus": "Explore the campus",
  "Un espace pensé pour": "A space designed for",
  "votre réussite": "your success",
  "Informations Pratiques": "Practical information",
  "Équipements": "Facilities",
  "Visite Virtuelle 360°": "360° virtual tour",
  "Bientôt disponible": "Coming soon",
  "Venez découvrir notre campus !": "Come and discover our campus!",
  "Réseau des Diplômés": "Alumni network",
  "partout dans le monde": "around the world",
  "Les Alumni à la une": "Alumni highlights",
  "Le réseau en action": "The network in action",
  "Secteurs d'activité de nos diplômés": "Our graduates' sectors",
  "Rejoignez-nous !": "Join us!",
  "Devenir mentor": "Become a mentor",
  "Mettez à jour votre profil": "Update your profile",
  "Rejoignez le réseau LinkedIn": "Join the LinkedIn network",
  "Foire Aux Questions": "Frequently Asked Questions",
  "Des questions ?": "Have questions?",
  "On a les réponses": "We have the answers",
  "Formulaire de contact": "Contact form",
  "Brochures": "Brochures",
  "Téléchargements": "Downloads",
  "Nos brochures par programme": "Brochures by programme",
  "Aperçu": "Preview",
  "Télécharger": "Download",
  "Besoin d'aide ?": "Need help?",
  "Vous ne trouvez pas votre brochure ?": "Can't find your brochure?",
  "Réinitialiser": "Reset",
  "Filtres actifs :": "Active filters:",
  "Toutes les certifications": "All certifications",
  "Grille": "Grid",
  "Tableau": "Table",
  "Organismes :": "Providers:",
  "Tous": "All",
  "Détails": "Details",
  "Aucune formation trouvée": "No programmes found",
  "Afficher toutes les formations": "Show all programmes",
  "Garantie d'excellence EBS": "EBS excellence guarantee",
  "Certifications IA": "AI certifications",
  "Pourquoi l'IA dans chaque filière ?": "Why AI in every field?",
  "Compétences fondamentales": "Core skills",
  "Les 5 compétences IA que maîtrisent": "The 5 AI skills mastered by",
  "TOUS": "ALL",
  "Une décision stratégique, pionnière en Tunisie.": "A strategic decision, pioneering in Tunisia.",
  "Notre Histoire": "Our history",
  "Les 4 piliers d'EBS": "EBS's 4 pillars",
  "EBS en chiffres": "EBS in numbers",
  "Accréditations & Reconnaissance": "Accreditations & recognition",
  "Services étudiants": "Student services",
  "Tout pour réussir": "Everything you need to succeed",
  "Notre Mission": "Our mission",
  "Nos Valeurs": "Our values",
  "Ils nous font confiance": "They trust us",
  "Pourquoi EBS ?": "Why EBS?",
  "Collaborer avec EBS": "Work with EBS",
  "Processus": "Process",
  "Devenir Partenaire": "Become a partner",
  "Demande envoyée !": "Request sent!",
  "Profil type": "Typical profile",
  "Page not found": "Page not found",
  "Oops! Page not found": "Oops! Page not found",
  "Hmm. We’re having trouble finding that site. Try again later or Check your network connection.": "We’re having trouble finding that page. Try again later or check your network connection.",
  "Back to Home": "Back to home",
  "Université privée agréée": "Approved private university",
  "Nos Fondamentaux": "Our foundations",
  "Notre Vision": "Our vision",
  "Ce que nous faisons chaque jour": "What we do every day",
  "Les 5 piliers qui nous définissent": "The 5 pillars that define us",
  "Rejoignez une université qui a une vision.": "Join a university with a vision.",
  "Vous souhaitez rejoindre notre équipe enseignante ?": "Would you like to join our teaching team?",
  "Corps Enseignant": "Faculty",
  "Un corps enseignant d'excellence,": "A faculty of excellence,",
  "au croisement de l'académie et de l'entreprise": "at the intersection of academia and industry",
  "Nos enseignants allient excellence académique et expérience professionnelle. Enseignants-chercheurs, experts et dirigeants d'entreprise partagent leur expertise et transmettent des compétences en phase avec les réalités du marché.": "Our faculty combine academic excellence with professional experience. Researchers, experts and business leaders share their expertise and teach skills aligned with the realities of the market.",
  "Taux d'insertion": "Employment rate",
  "Filières ouvertes": "Open fields",
  "Nos partenaires économiques": "Our corporate partners",
  "Recrutez les talents de demain,": "Recruit tomorrow's talent,",
  "dès aujourd'hui": "today",
  "Pourquoi recruter chez EBS": "Why recruit from EBS",
  "Quatre façons de travailler avec nos talents": "Four ways to work with our talent",
  "Comment devenir partenaire ?": "How do you become a partner?",
  "Formulaire de partenariat": "Partnership form",
  "Prêt à collaborer ?": "Ready to collaborate?",
  "Rejoignez notre réseau de partenaires économiques.": "Join our corporate partner network.",
  "Fondation d'EBS": "EBS is founded",
  "Premiers partenariats": "First partnerships",
  "Expansion internationale": "International expansion",
  "Le virage de l'IA": "The AI transition",
  "Année de fondation": "Year founded",
  "Diplômes disponibles": "Degrees available",
  "Certifications incluses": "Certifications included",
  "Taux de réussite": "Success rate",
  "Partenaires internationaux": "International partners",
  "Président Fondateur": "Founding President",
  "Le mot du Président Fondateur": "A word from the Founding President",
  "Plus de 12 ans d'excellence": "More than 12 years of excellence",
  "Qualité de l'Enseignement": "Teaching quality",
  "Pédagogie Innovante": "Innovative teaching",
  "Développement Personnel et Professionnel": "Personal and professional development",
  "Ouverture sur l'Environnement": "Openness to the world",
  "Career Center": "Career Centre",
  "Centre de Certification": "Certification Centre",
  "Bureau International": "International Office",
  "Bibliothèque & E-Learning": "Library & E-Learning",
  "Tutorat & Soutien": "Tutoring & support",
  "Vie étudiante": "Student life",
  "Concrètement chez EBS :": "In practice at EBS:",
  "Excellence académique": "Academic excellence",
  "Innovation pédagogique": "Educational innovation",
  "Ouverture internationale": "International outlook",
  "Employabilité réelle": "Real employability",
  "Proximité & Accompagnement": "Personal support",
  "Ce qui nous anime chaque jour": "What drives us every day",
  "Ce qui nous définit": "What defines us",
  "Recrutement · Stage · Alternance · Partenariat": "Recruitment · Internship · Work-study · Partnership",
  "Talents Certifiés": "Certified talent",
  "Opérationnels Rapidement": "Operational quickly",
  "Bilingues & Internationaux": "Bilingual & international",
  "Recrutement Sans Risque": "Risk-free recruitment",
  "Le plus demandé": "Most requested",
  "Immersion en entreprise": "Company immersion",
  "Projet Réel": "Real project",
  "Multi-certifié": "Multi-certified",
  "Maîtrise de l'IA": "AI mastery",
  "Expérience pratique": "Practical experience",
  "Rapidement opérationnel": "Operational quickly",
  "Profil international": "International profile",
  "Exprimez votre Intérêt": "Express your interest",
  "Nous Échangeons": "We talk",
  "Convention Signée": "Agreement signed",
  "Votre entreprise": "Your company",
  "Personne à contacter": "Contact person",
  "Type de partenariat": "Partnership type",
  "Votre projet": "Your project",
  "Envoyer une autre demande": "Send another request",
  "Envoyer ma demande": "Send my request",
  "Recrutement": "Recruitment",
  "Stage": "Internship",
  "Alternance": "Work-study",
  "Formation Continue": "Continuing education",
  "Événements": "Events",
  "Toutes les sections sauf Lettres et Sport": "All sections except Literature and Sport",
  "Bac+3 requis": "Bachelor's degree required",
  "3 destinations": "3 destinations",
  "4 Masters": "4 Master's programmes",
  "2 ans": "2 years",
  "3 ans": "3 years",
  "6 semestres": "6 semesters",
  "4 semestres": "4 semesters",
  "7 500 DT / An": "7,500 DT / year",
  "9 500 DT / An": "9,500 DT / year",
  "8 500 DT / An": "8,500 DT / year",
  "6 900 DT / An": "6,900 DT / year",
  "Parcourez et téléchargez les brochures de nos programmes. Retrouvez toutes les informations sur les cursus, certifications, débouchés et partenariats.": "Browse and download our programme brochures. Find all the information about courses, certifications, career opportunities and partnerships.",
  "Sélectionnez le programme qui vous intéresse et téléchargez sa brochure détaillée.": "Select the programme that interests you and download its detailed brochure.",
  "Contactez notre équipe pédagogique pour obtenir la brochure du programme qui vous intéresse.": "Contact our academic team to get the brochure for the programme that interests you.",
  "L'IA n'est plus une": "AI is no longer an",
  "C'est une": "It is an",
  "Culture IA": "AI literacy",
  "IA appliquées": "Applied AI",
  "recommandées": "recommended",
  "Formations rattachées": "Linked programmes",
  "Compétences requises": "Required skills",
  "Catalogue international de certifications": "International certification catalogue",
  "Incluses et gratuites": "Included and free",
  "Justificatifs Officiels": "Official credentials",
  "Une question sur nos programmes ? Une demande d'inscription ? Notre équipe vous répond sous 24h.": "A question about our programmes? An application request? Our team replies within 24 hours.",
  "Y a-t-il un concours d'entrée ?": "Is there an entrance exam?",
  "Quand ouvrent les inscriptions ?": "When does enrolment open?",
  "Peut-on s'inscrire en cours d'année ?": "Can I enrol during the academic year?",
  "EBS est-elle agréée par l'État tunisien ?": "Is EBS approved by the Tunisian State?",
  "Des facilités de paiement ou des réductions sont-elles proposées ?": "Are payment plans or discounts available?",
  "Quels Baccalauréats permettent de s'inscrire en Licence ?": "Which Baccalaureate streams allow enrolment in a Bachelor's programme?",
  "Puis-je intégrer EBS après avoir commencé mes études dans une autre université ?": "Can I join EBS after starting my studies at another university?",
  "Puis-je poursuivre mes études à l'étranger après EBS ?": "Can I continue my studies abroad after EBS?",
  "Dois-je choisir le Parcours International dès ma première année ?": "Do I have to choose the International pathway in my first year?",
  "Peut-on intégrer un Master EBS avec une Licence obtenue dans une autre université ?": "Can I join an EBS Master's programme with a Bachelor's degree from another university?",
  "Les étudiants internationaux peuvent-ils s'inscrire à EBS ?": "Can international students enrol at EBS?",
  "EBS accompagne-t-elle les étudiants pour le visa ?": "Does EBS help students with visa applications?",
  "La pré-inscription est-elle définitive ?": "Is the initial application final?",
  "Puis-je être conseillé avant de choisir ma filière ?": "Can I get advice before choosing my field?",
  "Non. L'admission à EBS se fait sur étude du dossier académique et de la motivation du candidat.": "No. EBS admissions are based on an academic file and the applicant's motivation.",
  "Les inscriptions sont ouvertes chaque année pour la prochaine rentrée universitaire, dans la limite des places disponibles.": "Enrolment opens each year for the next academic year, subject to available places.",
  "Notre équipe est disponible pour répondre à toutes vos questions.": "Our team is available to answer all your questions.",
  "Vous n'avez pas trouvé": "Could not find",
  "votre réponse ?": "your answer?",
  "Notre équipe admission vous accompagne à chaque étape pour préparer votre rentrée dans les meilleures conditions.": "Our admissions team supports you at every step as you prepare to start your studies.",
  "Lundi - Vendredi": "Monday - Friday",
  "Samedi": "Saturday",
  "Dimanche : Fermé": "Sunday: Closed",
  "Écrire": "Write to us",
  "Téléphone": "Phone",
  "Adresse": "Address",
  "Voir sur la carte": "View on map",
  "Candidatures 2026–2027 ouvertes. Effectuez votre préinscription dès maintenant.": "Applications for 2026–2027 are open. Apply now.",
  "Visitez notre campus et rencontrez notre équipe pédagogique.": "Visit our campus and meet our academic team.",
  "Échangez directement avec notre équipe sur WhatsApp.": "Chat directly with our team on WhatsApp.",
  "Par téléphone, email, WhatsApp ou": "By phone, email, WhatsApp or",
  "directement sur place.": "in person.",
  "Merci pour votre message. Notre équipe vous répondra dans les": "Thank you for your message. Our team will reply within",
  "les plus brefs délais.": "as soon as possible.",
  "Votre nom": "Your name",
  "Sélectionnez": "Select",
  "Votre demande de visite a bien été reçue.": "Your visit request has been received.",
  "Fermer": "Close",
  "Envoi...": "Sending...",
  "Envoyer ma candidature": "Send my application",
  "Merci !": "Thank you!",
};

function translateNode(node: ReactNode): ReactNode {
  if (typeof node === "string") {
    let result = node;
    for (const [from, to] of Object.entries(translations).sort((a, b) => b[0].length - a[0].length)) {
      result = result.replaceAll(from, to);
    }
    return result;
  }
  if (Array.isArray(node)) return node.map(translateNode);
  if (node && typeof node === "object" && "type" in node && "props" in node) {
    const element = node as ReactElement<{ children?: ReactNode }>;
    const props = Object.fromEntries(Object.entries(element.props).map(([key, value]) => {
      if (key === "href" || key === "src" || key === "className" || key === "style") return [key, value];
      if (typeof value === "string") return [key, translateNode(value)];
      if (Array.isArray(value)) return [key, value.map(translateNode)];
      if (key === "children") return [key, translateNode(value)];
      return [key, value];
    }));
    return { ...element, props } as ReactElement;
  }
  return node;
}

export function LocalizedRoute({ children }: { children: ReactNode }) {
  const locale = useLocale();
  return <>{locale === "en" ? translateNode(children) : children}</>;
}
