import type { ProgramLPData } from "@/components/program";

export const licences: Record<string, ProgramLPData> = {
  management: {
    slug: "management",
    type: "licence",
    title: "Licence en Management",
    tagline: "Devenez le manager augmenté par l'IA que les entreprises s'arrachent.",
    pitch: "La Licence en Management d'EBS forme des leaders opérationnels capables de piloter des équipes, des projets et des organisations dans un environnement digital en constante évolution. Vous deviendrez un véritable AI-Driven Manager, utilisant l'IA pour automatiser les tâches chronophages et vous concentrer sur la stratégie humaine.",
    color: "#2196F3",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 57,
    publicCible: [
      "Bacheliers toutes séries · 18–22 ans",
      "Étudiants souhaitant se réorienter vers le management",
      "Futurs entrepreneurs, chefs de projet, consultants",
    ],
    modules: [
      { title: "Fondements du management et théories de l'organisation", description: "Introduction aux principes fondamentaux du management moderne, des théories classiques aux approches contemporaines." },
      { title: "Leadership et management des équipes", description: "Techniques de leadership, gestion des talents, motivation des équipes et résolution de conflits." },
      { title: "Gestion de projet (PMI PMBOK + Scrum + Kanban)", description: "Méthodologies de gestion de projet agiles et traditionnelles. Préparation aux certifications PMI et Scrum." },
      { title: "Stratégie d'entreprise et analyse de marché", description: "Analyse concurrentielle, positionnement stratégique et études de marché pour la prise de décision." },
      { title: "Business analytics et tableaux de bord décisionnels", description: "Analyse de données d'entreprise, création de dashboards et reporting pour le pilotage stratégique." },
      { title: "Management des Ressources Humaines", description: "Recrutement, formation, évaluation des performances et gestion des carrières dans l'organisation." },
      { title: "Entrepreneuriat et création d'entreprise", description: "Du business model à la création effective : aspects juridiques, financiers et stratégiques." },
      { title: "Droit des affaires et environnement réglementaire", description: "Cadre juridique de l'entreprise, droit commercial, droit du travail et réglementation tunisienne." },
      { title: "Intelligence Artificielle appliquée au management", description: "Utilisation de l'IA pour la prise de décision, la prédiction et l'automatisation des processus managériaux." },
      { title: "Anglais des affaires & communication professionnelle", description: "Anglais business, présentations, négociations et communication écrite professionnelle." },
      { title: "Stage professionnel 3 mois (L3)", description: "Immersion en entreprise pour appliquer les compétences acquises et développer son réseau professionnel." },
    ],
    certifications: [
      { name: "Google Project Management Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Scrum Fundamentals Certified SFC™", provider: "ScrumStudy", level: "Débutant" },
      { name: "PMI Kickoff", provider: "PMI", level: "Débutant" },
      { name: "PMI Disciplined Agile Essentials", provider: "PMI", level: "Intermédiaire" },
      { name: "IBM SkillsBuild Business Analyst", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Agile Essentials", provider: "Google", level: "Débutant" },
      { name: "BCG Strategy Consulting Simulation", provider: "Forage", level: "Intermédiaire" },
      { name: "PwC Management Consulting", provider: "PwC", level: "Intermédiaire" },
      { name: "Lean Six Sigma White Belt", provider: "ScrumStudy", level: "Débutant" },
      { name: "Google Business Intelligence Certificate", provider: "Google", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Maîtrise en Gestion de Projets", partenaire: "UQAT — Canada", details: "Accès direct depuis la Licence Management EBS — Convention inter-universitaire" },
      { programme: "Master Grande École Management", partenaire: "EM Normandie — France", details: "Convention directe EBS → EM Normandie" },
      { programme: "Master Management", partenaire: "PSB Paris School of Business — France", details: "Admission facilitée via convention EBS" },
      { programme: "Master Management des Entreprises", partenaire: "IDRAC / IFAG (Groupe FIGS) — France", details: "Multi-campus France · Accès depuis Licence EBS" },
    ],
    debouches: [
      "AI-Driven Manager",
      "Chef de projet junior",
      "Manager d'équipe",
      "Business Analyst",
      "Responsable administratif",
      "Entrepreneur",
      "Chargé de développement commercial",
      "Responsable des opérations",
    ],
  },

  marketing: {
    slug: "marketing",
    type: "licence",
    title: "Licence en Marketing",
    tagline: "Maîtrisez le digital. Automatisez avec l'IA. Convertissez massivement.",
    pitch: "La Licence en Marketing d'EBS est la formation la plus complète en marketing digital en Tunisie. Du SEO à l'IA générative, de Google Ads au CRM — formez-vous pour devenir un AI-Driven Marketer combinant intuition créative et hyper-puissance algorithmique.",
    color: "#E91E8C",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 81,
    publicCible: [
      "Bacheliers créatifs et analytiques · 18–22 ans",
      "Passionnés du digital, des réseaux sociaux et de la communication",
      "Futurs directeurs marketing, growth hackers, SEO managers",
    ],
    modules: [
      { title: "Fondements du marketing et comportement consommateur", description: "Comprendre les mécanismes psychologiques et sociologiques qui guident les décisions d'achat." },
      { title: "Marketing digital stratégique et e-commerce", description: "Stratégies omnicanal, e-commerce, marketplaces et optimisation des tunnels de conversion." },
      { title: "SEO / SEA et référencement (Google Ads officiel)", description: "Optimisation pour les moteurs de recherche et campagnes publicitaires Google Ads." },
      { title: "Social media marketing & community management", description: "Stratégies de contenu, gestion de communautés et marketing d'influence sur les principales plateformes." },
      { title: "Google Analytics 4 — analytics web avancé", description: "Mesure, analyse et optimisation des performances web avec GA4." },
      { title: "Content marketing, copywriting et storytelling", description: "Création de contenu engageant, techniques de copywriting et narration de marque." },
      { title: "CRM et gestion de la relation client (HubSpot)", description: "Gestion du cycle de vie client, automatisation marketing et fidélisation avec HubSpot." },
      { title: "LinkedIn Marketing & social selling B2B", description: "Stratégies de prospection et de vente sociale sur LinkedIn pour le marché B2B." },
      { title: "Email marketing & automation (HubSpot)", description: "Campagnes email, segmentation, automation et nurturing de leads." },
      { title: "IA appliquée au marketing : SEMrush AI, génération de contenu", description: "Utilisation de l'IA pour le SEO, la création de contenu et l'optimisation des campagnes." },
      { title: "Publicité programmatique (DV360, SA360)", description: "Achat média automatisé, RTB et optimisation des campagnes display et vidéo." },
      { title: "Stage 3 mois en agence ou département marketing", description: "Expérience professionnelle en agence de communication ou service marketing d'entreprise." },
    ],
    certifications: [
      { name: "Google Fundamentals of Digital Marketing", provider: "Google", level: "Débutant" },
      { name: "Google Analytics Certification (GA4)", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Search Certification", provider: "Google", level: "Intermédiaire" },
      { name: "Google Ads Display Certification", provider: "Google", level: "Intermédiaire" },
      { name: "HubSpot Digital Marketing", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Content Marketing", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Inbound Marketing", provider: "HubSpot", level: "Débutant" },
      { name: "SEO Essentials (AI Optimization)", provider: "SEMrush", level: "Débutant" },
      { name: "Technical SEO & AI Search Essentials", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy", provider: "LinkedIn", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Master Grande École Digital Marketing", partenaire: "EM Normandie — France", details: "Spécialisation marketing digital et international" },
      { programme: "MSc Digital Marketing & Social Media", partenaire: "Sup'de Com — France", details: "L'école de tous les métiers de la communication" },
      { programme: "Master Marketing", partenaire: "PSB Paris — France", details: "Accès direct depuis Licence Marketing EBS" },
      { programme: "Master Marketing & Communication", partenaire: "Éklore ed. — France", details: "École de management innovante Groupe FIGS" },
    ],
    debouches: [
      "AI-Driven Marketer",
      "Digital Marketing Manager",
      "SEO / SEA Specialist",
      "Social Media Manager",
      "Growth Hacker",
      "Data Analyst Marketing",
      "Responsable CRM",
      "Chef de produit digital",
      "Directeur Marketing (trajectoire 5–7 ans)",
    ],
  },

  finance: {
    slug: "finance",
    type: "licence",
    title: "Licence en Finance",
    tagline: "Dominez la finance algorithmique et les données de marché.",
    pitch: "La Licence en Finance d'EBS vous prépare aux métiers de la finance moderne. En alliant les certifications Bloomberg à la maîtrise des données, vous devenez un AI-Driven Financial Consultant avec un avantage compétitif absolu sur le marché de l'emploi.",
    color: "#00BCD4",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 64,
    publicCible: [
      "Bacheliers scientifiques ou économiques · 18–22 ans",
      "Futurs analystes financiers, banquiers, contrôleurs de gestion",
      "Passionnés de marchés financiers et d'économie",
    ],
    modules: [
      { title: "Comptabilité générale et analytique", description: "Principes comptables, écritures, bilan, compte de résultat et analyse des coûts." },
      { title: "Analyse financière et diagnostics d'entreprise", description: "Ratios financiers, analyse de la rentabilité, de la solvabilité et diagnostic global." },
      { title: "Mathématiques financières et statistiques", description: "Calculs actuariels, probabilités, statistiques appliquées à la finance." },
      { title: "Marchés financiers et produits d'investissement", description: "Actions, obligations, dérivés, ETF et autres instruments financiers." },
      { title: "Finance d'entreprise et évaluation (DCF, comparables)", description: "Valorisation d'entreprise, choix d'investissement et structure du capital." },
      { title: "Contrôle de gestion et reporting financier", description: "Budgets, tableaux de bord, analyse des écarts et reporting." },
      { title: "Fintech et finance numérique", description: "Blockchain, crypto-actifs, robo-advisors et disruption du secteur financier." },
      { title: "ESG et finance durable", description: "Critères environnementaux, sociaux et de gouvernance dans les décisions d'investissement." },
      { title: "Python pour la finance (initiation)", description: "Programmation Python appliquée à l'analyse financière et à la modélisation." },
      { title: "Utilisation du terminal Bloomberg", description: "Maîtrise du terminal Bloomberg, outil de référence des professionnels de la finance." },
      { title: "Stage 3 mois en banque, cabinet ou entreprise", description: "Immersion professionnelle dans le secteur financier." },
    ],
    certifications: [
      { name: "Bloomberg Market Concepts (BMC)", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg ESG Certificate", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Spreadsheet Analysis", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Google Data Analytics Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "Goldman Sachs: Risk (Forage)", provider: "Goldman Sachs", level: "Intermédiaire" },
      { name: "Citi: Investment Banking (Forage)", provider: "Citi Bank", level: "Intermédiaire" },
      { name: "JPMorgan: Investment Banking (Forage)", provider: "JPMorgan", level: "Intermédiaire" },
      { name: "IBM Finance & Accounting Essentials", provider: "IBM", level: "Débutant" },
      { name: "Oliver Wyman: Financial Services & Climate", provider: "Forage", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Maîtrise en Sciences de la Gestion — Finance", partenaire: "UQAT — Canada", details: "Accès direct — Convention inter-universitaire EBS–UQAT" },
      { programme: "Master Finance & Banque", partenaire: "EM Normandie — France", details: "Spécialisation marchés financiers et banque" },
      { programme: "Master Finance d'entreprise & Expertise Comptable", partenaire: "IGEFI — France", details: "École spécialisée finance et expertise comptable" },
      { programme: "MSc Finance de Marché", partenaire: "PSB Paris — France", details: "M&A, gestion de portefeuille, finance de marché" },
    ],
    debouches: [
      "AI-Driven Financial Consultant",
      "Analyste financier",
      "Contrôleur de gestion",
      "Chargé de clientèle bancaire",
      "Auditeur junior",
      "Conseiller en gestion de patrimoine",
      "Responsable comptable",
      "Analyste crédit",
    ],
  },


  "informatique-ia": {
    slug: "informatique-ia",
    type: "licence",
    title: "Licence Informatique — Intelligence Artificielle",
    tagline: "Construisez les intelligences de demain.",
    pitch: "La Licence Informatique Parcours IA d'EBS est la formation la plus pointue en Intelligence Artificielle disponible en Tunisie. Machine learning, deep learning, data science, NLP, agents IA — avec les certifications Harvard, DeepLearning.AI, IBM et Google Cloud.",
    color: "#9C27B0",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 87,
    publicCible: [
      "Bacheliers scientifiques (Math, Info, Sciences) · 18–22 ans",
      "Passionnés de programmation, data et intelligence artificielle",
      "Futurs data scientists, ML engineers, chercheurs en IA",
    ],
    modules: [
      { title: "Algorithmique avancée et programmation Python", description: "Structures de données avancées, complexité algorithmique et programmation Python intensive." },
      { title: "Mathématiques pour l'IA", description: "Algèbre linéaire, probabilités, calcul différentiel et optimisation pour le machine learning." },
      { title: "Machine Learning supervisé et non supervisé (scikit-learn)", description: "Régression, classification, clustering et évaluation de modèles ML." },
      { title: "Deep Learning — réseaux de neurones (TensorFlow, PyTorch)", description: "Architectures de réseaux de neurones, rétropropagation et frameworks modernes." },
      { title: "Natural Language Processing (NLP) & Large Language Models", description: "Traitement du langage naturel, transformers et LLMs comme GPT et BERT." },
      { title: "Computer Vision et traitement d'images", description: "CNN, détection d'objets, segmentation et applications de vision par ordinateur." },
      { title: "MLOps et déploiement de modèles en production", description: "CI/CD pour le ML, monitoring de modèles et infrastructure de déploiement." },
      { title: "Agents IA autonomes et LangChain", description: "Création d'agents IA, chaînes de traitement et intégration avec les LLMs." },
      { title: "Big Data : Spark, Hadoop, Databricks Lakehouse", description: "Traitement distribué, data lakes et architectures big data modernes." },
      { title: "Architecture Cloud IA (Google Cloud, AWS)", description: "Services cloud pour l'IA, GPU as a service et déploiement scalable." },
      { title: "Projet de fin d'études IA appliqué à un cas réel", description: "Projet de recherche ou industriel complet de bout en bout." },
    ],
    certifications: [
      { name: "CS50's Introduction to AI with Python", provider: "Harvard", level: "Intermédiaire" },
      { name: "Machine Learning Specialization", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "Deep Learning Specialization", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "TensorFlow Developer Professional", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
      { name: "AI Agents in your Workflows", provider: "Databricks", level: "Intermédiaire" },
      { name: "IBM: Applied Data Science", provider: "IBM", level: "Avancé" },
      { name: "Data Science with Python", provider: "IBM Cognitive", level: "Intermédiaire" },
      { name: "Google Advanced Data Analytics", provider: "Google", level: "Avancé" },
      { name: "Google Cloud: Data Engineer", provider: "Google", level: "Avancé" },
    ],
    internationalPathways: [
      { programme: "Master of Science Informatique — Spécialisation IA", partenaire: "Epitech — France", details: "L'une des meilleures écoles informatiques en France — 15 campus" },
      { programme: "Expert Informatique & Systèmes d'Information", partenaire: "EPSI — France", details: "Ingénierie informatique — Titre RNCP Bac+5" },
      { programme: "MSc Information Technology — Intelligent Systems", partenaire: "GUtech — Oman", details: "Partenariat RWTH Aachen — Accès au marché du Golfe" },
      { programme: "Maîtrise en Sciences de la Gestion — Informatique", partenaire: "UQAT — Canada", details: "Perspectives d'immigration qualifiée Canada" },
    ],
    debouches: [
      "Data Scientist",
      "Machine Learning Engineer",
      "AI Developer / LLM Engineer",
      "Data Analyst",
      "Research Engineer",
      "NLP Specialist",
      "MLOps Engineer",
      "AI Product Manager",
    ],
  },

  cybersecurite: {
    slug: "cybersecurite",
    type: "licence",
    title: "Licence Informatique — Cybersécurité",
    tagline: "Devenez la première ligne de défense du monde numérique.",
    pitch: "La Licence Cybersécurité d'EBS forme les experts en sécurité informatique dont le marché manque cruellement. Ethical hacking, forensics, défense réseau, cloud security — avec Cisco, Fortinet, Google et Harvard.",
    color: "#FF9800",
    niveau: "Bac+3",
    duree: "3 ans",
    semestres: 6,
    totalCerts: 63,
    publicCible: [
      "Bacheliers scientifiques (Math, Info) · 18–22 ans",
      "Passionnés de sécurité informatique, hacking éthique, réseaux",
      "Futurs SOC analysts, pentesters, RSSI, consultants cyber",
    ],
    modules: [
      { title: "Fondements réseaux et protocoles TCP/IP", description: "Couches OSI, protocoles réseau, routage et commutation avancés." },
      { title: "Systèmes Linux avancé (Cisco NetAcad certification)", description: "Administration Linux, durcissement système et scripts de sécurité." },
      { title: "Programmation Python pour la cybersécurité", description: "Automatisation de tâches de sécurité, scripting d'exploitation et analyse forensique." },
      { title: "Ethical hacking et tests de pénétration (méthodologie)", description: "Reconnaissance, scanning, exploitation et post-exploitation éthique." },
      { title: "Sécurité des applications web (OWASP Top 10)", description: "Injection SQL, XSS, CSRF et sécurisation des applications web modernes." },
      { title: "Cryptographie moderne et PKI", description: "Chiffrement symétrique/asymétrique, certificats, signatures et infrastructures à clés publiques." },
      { title: "Incident Response et forensics numérique", description: "Détection, confinement, éradication et analyse forensique post-incident." },
      { title: "SOC : SIEM, analyse de logs, gestion des alertes", description: "Opérations de sécurité, corrélation d'événements et réponse aux incidents." },
      { title: "Cloud Security (AWS, Azure, GCP)", description: "Sécurisation des environnements cloud, IAM et conformité." },
      { title: "DevSecOps et sécurité dans le pipeline CI/CD", description: "Intégration de la sécurité dans les processus de développement et de déploiement." },
      { title: "Gestion des risques cyber (ISO 27001, NIST Framework)", description: "Analyse des risques, politiques de sécurité et conformité réglementaire." },
    ],
    certifications: [
      { name: "Google Cybersecurity Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "CS50's Intro to Cybersecurity", provider: "Harvard", level: "Débutant" },
      { name: "Ethical Hacker", provider: "Cisco NetAcad", level: "Intermédiaire" },
      { name: "Cyber Threat Management", provider: "Cisco NetAcad", level: "Avancé" },
      { name: "FCF Cybersecurity Fundamentals", provider: "Fortinet", level: "Débutant" },
      { name: "FCA Cybersecurity Associate", provider: "Fortinet", level: "Intermédiaire" },
      { name: "Fortinet NSE Training Institute", provider: "Fortinet", level: "Avancé" },
      { name: "Mastercard: Cybersecurity (Forage)", provider: "Mastercard", level: "Intermédiaire" },
      { name: "PwC: Cyber Security Consulting (Forage)", provider: "PwC", level: "Intermédiaire" },
      { name: "EY: Technology Risk (Forage)", provider: "EY", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "Master of Science Informatique — Cybersécurité", partenaire: "Epitech — France", details: "Expert Cybersécurité — 15 campus France + 5 international" },
      { programme: "Expert Informatique — Cybersécurité", partenaire: "EPSI — France", details: "Formation cybersécurité reconnue — Titre RNCP Bac+5" },
      { programme: "MSc Information Technology — Cybersecurity", partenaire: "GUtech — Oman", details: "Partenariat RWTH Aachen — Ouverture marché du Golfe" },
      { programme: "Maîtrise Informatique", partenaire: "UQAT — Canada", details: "Résidence permanente facilitée via PEQ après diplôme" },
    ],
    debouches: [
      "SOC Analyst",
      "Pentester / Ethical Hacker",
      "Security Consultant",
      "Forensics Analyst",
      "Cybersecurity Architect",
      "Cloud Security Engineer",
      "GRC Analyst",
      "Threat Intelligence Analyst",
    ],
  },
};
