import type { ProgramLPData } from "@/components/program";

export const masters: Record<string, ProgramLPData> = {
  crm: {
    slug: "crm",
    type: "master",
    title: "Master CRM Marketing & Transformation Digitale",
    tagline: "Pilotez la relation client à l'ère de l'intelligence artificielle.",
    pitch: "Le Master CRM & Transformation Digitale d'EBS forme les architectes de la relation client de demain. HubSpot, n8n, IBM Watsonx — vous maîtrisez les outils qui transforment les données clients en croissance business.",
    color: "#E91E63",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 73,
    publicCible: [
      "Licenciés en Marketing, Management, Informatique",
      "Professionnels souhaitant évoluer vers le CRM ou le digital",
      "Futurs CRM managers, responsables transformation digitale",
    ],
    modules: [
      { title: "Architecture CRM et stratégie de données clients", description: "Conception et déploiement d'une stratégie CRM orientée données." },
      { title: "HubSpot CRM complet (Marketing Hub, Sales Hub, Service Hub)", description: "Maîtrise de l'écosystème HubSpot pour le marketing, les ventes et le service client." },
      { title: "Marketing automation et nurturing multicanal", description: "Automatisation email, WhatsApp, SMS et campagnes cross-canal." },
      { title: "Transformation digitale des organisations", description: "Frameworks BCG/McKinsey pour conduire le changement digital en entreprise." },
      { title: "Data marketing et analytics avancé (GA4, Looker Studio, Power BI)", description: "Analyse de données marketing, dashboards et prise de décision data-driven." },
      { title: "IA appliquée au CRM : chatbots, scoring prédictif, Watsonx IBM", description: "Intelligence artificielle pour la personnalisation et l'automatisation de la relation client." },
      { title: "n8n Automation : workflows no-code et agents IA", description: "Automatisation des processus métier sans code avec n8n." },
      { title: "Social selling et LinkedIn Marketing avancé", description: "Stratégies de vente sociale et prospection B2B sur LinkedIn." },
      { title: "E-commerce, UX et optimisation des conversions (CRO)", description: "Optimisation des tunnels de vente en ligne et expérience utilisateur." },
      { title: "SEO / SEA avancé et acquisition digitale", description: "Stratégies avancées de référencement et d'acquisition de trafic qualifié." },
      { title: "Projet de transformation digitale sur cas d'entreprise réel", description: "Mission de consulting sur un cas réel d'entreprise partenaire." },
    ],
    certifications: [
      { name: "HubSpot CRM Software Certification", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Hub Software", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Inbound Marketing Optimization", provider: "HubSpot", level: "Avancé" },
      { name: "HubSpot Revenue Operations", provider: "HubSpot", level: "Intermédiaire" },
      { name: "n8n Automation Level 1 & 2", provider: "n8n", level: "Intermédiaire" },
      { name: "IBM Watsonx Orchestrate", provider: "IBM", level: "Intermédiaire" },
      { name: "Google Analytics Certification", provider: "Google", level: "Intermédiaire" },
      { name: "Google Digital Marketing & E-commerce", provider: "Google", level: "Intermédiaire" },
      { name: "SEMrush: AI-Powered Marketer", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy", provider: "LinkedIn", level: "Intermédiaire" },
    ],
    internationalPathways: [
      { programme: "MSc Digital Marketing & Communication", partenaire: "EM Normandie — France", details: "CRM, digital et international" },
      { programme: "MSc Digital Marketing & Social Media", partenaire: "Sup'de Com — France", details: "Communication et marketing digital" },
      { programme: "Master Marketing & Digital Business", partenaire: "PSB Paris — France", details: "Data marketing, e-commerce, CRM" },
      { programme: "MBA Administration des Affaires", partenaire: "UQAT — Canada", details: "Option management et transformation digitale" },
    ],
    debouches: [
      "CRM Manager",
      "Marketing Automation Specialist",
      "Digital Marketing Manager",
      "Growth Hacker",
      "Responsable Transformation Digitale",
      "RevOps Manager",
      "Chief Digital Officer (trajectoire 5–7 ans)",
      "E-commerce Manager",
    ],
  },

  startups: {
    slug: "startups",
    type: "master",
    title: "Master Management de Projets Innovants & Startups",
    tagline: "Lancez. Innovez. Scalez.",
    pitch: "Le Master Startups & Projets Innovants d'EBS est le programme pour ceux qui veulent changer les règles du jeu. PMI, Scrum, DevOps, Lean Startup, VC — vous sortez avec les outils, les certifications et le réseau pour transformer une idée en entreprise.",
    color: "#5E35B1",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 59,
    publicCible: [
      "Licenciés en Management, Informatique, Finance",
      "Entrepreneurs en herbe et porteurs de projets",
      "Professionnels souhaitant manager l'innovation en entreprise",
    ],
    modules: [
      { title: "Management de projets avancé (PMI PMBOK 7 + Agile Scrum)", description: "Gestion de projet professionnelle, certification PMP-compatible." },
      { title: "Lean Startup et validation de modèles d'affaires", description: "Méthodologie Lean Startup d'Ash Maurya pour valider rapidement des idées." },
      { title: "Design Thinking et innovation centrée utilisateur", description: "Processus créatif de résolution de problèmes orienté besoins utilisateurs." },
      { title: "Entrepreneuriat : de l'idée à la création d'entreprise", description: "Parcours complet de création : statuts juridiques, business plan, financement." },
      { title: "Financement des startups (VC, Business Angels, crowdfunding)", description: "Levée de fonds, valorisation, term sheets et relations investisseurs." },
      { title: "Product Management et roadmap produit agile", description: "Gestion de produit, priorisation, user stories et MVP." },
      { title: "DevOps et déploiement continu (IBM Pro Certificate)", description: "Intégration et déploiement continus, infrastructure as code." },
      { title: "IA et automatisation pour startups (n8n, agents IA)", description: "Automatisation des processus startup avec l'IA et les outils no-code." },
      { title: "Pitch et communication pour investisseurs", description: "Techniques de pitch, storytelling et préparation aux levées de fonds." },
      { title: "Réglementation startup : statuts, droit de l'innovation", description: "Cadre juridique de l'innovation, protection intellectuelle et contrats." },
      { title: "Projet startup : de l'idée au MVP encadré par des mentors", description: "Création d'un produit minimum viable avec mentorat de professionnels." },
    ],
    certifications: [
      { name: "Google Project Management Certificate", provider: "Google", level: "Intermédiaire" },
      { name: "PMI Kickoff", provider: "PMI", level: "Débutant" },
      { name: "PMI Disciplined Agile Essentials", provider: "PMI", level: "Intermédiaire" },
      { name: "Scrum Fundamentals Certified SFC™", provider: "ScrumStudy", level: "Débutant" },
      { name: "Scrum with AI Certified SAC™", provider: "ScrumStudy", level: "Intermédiaire" },
      { name: "IBM DevOps Pro Certificate", provider: "IBM", level: "Avancé" },
      { name: "BCG Venture & Business Builds (Forage)", provider: "BCG", level: "Avancé" },
      { name: "Siemens Mobility: Project Manager (Forage)", provider: "Siemens", level: "Intermédiaire" },
      { name: "n8n Automation Level 1 & 2", provider: "n8n", level: "Intermédiaire" },
      { name: "Google Agile Essentials", provider: "Google", level: "Débutant" },
    ],
    internationalPathways: [
      { programme: "Maîtrise en Gestion de Projets", partenaire: "UQAT — Canada", details: "Poursuite directe — Convention inter-universitaire EBS–UQAT" },
      { programme: "Master Grande École — Entrepreneuriat & Innovation", partenaire: "EM Normandie — France", details: "Spécialisation entrepreneuriat et innovation" },
      { programme: "Master Management des Organisations", partenaire: "Éklore ed. / IFAG (Groupe FIGS) — France", details: "Management et innovation — pédagogie orientée futur" },
      { programme: "Master Management des Entreprises", partenaire: "PSB Paris — France", details: "Gestion de projet, management stratégique" },
    ],
    debouches: [
      "Chef de Projet / Project Manager",
      "Product Manager / Product Owner",
      "Scrum Master / Agile Coach",
      "Entrepreneur / Co-fondateur de Startup",
      "Innovation Manager",
      "Business Development Manager",
      "Venture Builder",
      "CTO / COO Startup",
    ],
  },

  "ingenierie-financiere": {
    slug: "ingenierie-financiere",
    type: "master",
    title: "Master Ingénierie Financière",
    tagline: "Structurez. Valorisez. Investissez.",
    pitch: "Le Master Ingénierie Financière d'EBS forme les architectes des transactions financières complexes. M&A, dérivés, finance quantitative, ESG — avec Bloomberg et les simulations Goldman Sachs, JP Morgan et Citi, vous entrez directement dans la cour des grands.",
    color: "#00897B",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 64,
    publicCible: [
      "Licenciés en Finance, Management, Mathématiques appliquées",
      "Professionnels de la finance souhaitant se spécialiser",
      "Futurs banquiers d'affaires, analystes quant, ingénieurs financiers",
    ],
    modules: [
      { title: "Mathématiques financières avancées et statistiques", description: "Calcul stochastique, processus de Wiener, modèles de taux et statistiques avancées." },
      { title: "Théorie des marchés financiers et microstructure", description: "Formation des prix, liquidité, trading haute fréquence et régulation." },
      { title: "Ingénierie des produits dérivés", description: "Options, futures, swaps, produits structurés et stratégies de couverture." },
      { title: "Fusions & Acquisitions (M&A) et valorisation d'entreprise", description: "DCF, LBO, multiples comparables et due diligence financière." },
      { title: "Gestion de portefeuille et risk management", description: "VaR, CVaR, stress tests et allocation stratégique d'actifs." },
      { title: "Finance quantitative et Python Finance", description: "NumPy, pandas, scipy appliqués à la modélisation financière." },
      { title: "FinTech : blockchain, algorithmic trading, robo-advisors", description: "Technologies disruptives dans les services financiers." },
      { title: "Finance durable et investissement ESG", description: "Reporting extra-financier, scoring ESG et green bonds." },
      { title: "Modélisation financière avancée (Bloomberg Terminal, Excel)", description: "Construction de modèles financiers complexes sur Bloomberg et Excel." },
      { title: "Mémoire de recherche appliqué et soutenance", description: "Travail de recherche approfondi sur une problématique financière contemporaine." },
    ],
    certifications: [
      { name: "Bloomberg Market Concepts (BMC)", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Finance Fundamentals", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg ESG Certificate", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "Bloomberg Spreadsheet Analysis", provider: "Bloomberg", level: "Intermédiaire" },
      { name: "JP Morgan: Quantitative Research (Forage)", provider: "JP Morgan", level: "Avancé" },
      { name: "Goldman Sachs: Investment Banking (Forage)", provider: "Goldman Sachs", level: "Intermédiaire" },
      { name: "Citi: Markets Quantitative Analysis (Forage)", provider: "Citi", level: "Avancé" },
      { name: "Bank of America: Investment Banking (Forage)", provider: "Bank of America", level: "Intermédiaire" },
      { name: "Mathematics for ML & Data Science", provider: "DeepLearning.AI", level: "Intermédiaire" },
      { name: "Google Advanced Data Analytics", provider: "Google", level: "Avancé" },
    ],
    internationalPathways: [
      { programme: "Maîtrise en Sciences de la Gestion — Finance", partenaire: "UQAT — Canada", details: "Accès direct — Convention EBS–UQAT — Résidence permanente Canada possible" },
      { programme: "Master Finance & Banque d'investissement", partenaire: "EM Normandie — France", details: "Marchés financiers, M&A, ingénierie financière" },
      { programme: "Master Finance d'entreprise & Expertise Comptable", partenaire: "IGEFI — France", details: "Spécialiste finance et expertise comptable" },
      { programme: "MSc Finance de Marché", partenaire: "PSB Paris — France", details: "Finance quantitative, gestion de portefeuille, M&A" },
    ],
    debouches: [
      "Analyste en banque d'investissement",
      "Gestionnaire de portefeuille",
      "Risk Manager",
      "Quant Analyst",
      "Directeur financier (CFO) — trajectoire 7–10 ans",
      "FinTech Product Manager",
      "Conseiller en M&A",
      "Analyste ESG",
    ],
  },

  "marketing-digital-ia": {
    slug: "marketing-digital-ia",
    type: "master",
    title: "Master Marketing Digital & IA",
    tagline: "Pilotez la croissance. Maîtrisez l'IA. Dominez les marchés.",
    pitch: "Le Master Marketing Digital & IA d'EBS forme les directeurs marketing de demain, capables d'utiliser l'intelligence artificielle pour décupler les performances d'acquisition et de fidélisation.",
    color: "#E91E8C",
    niveau: "Bac+5",
    duree: "2 ans",
    semestres: 4,
    totalCerts: 81,
    publicCible: [
      "Licenciés en Marketing, Management, Informatique",
      "Professionnels souhaitant évoluer vers le marketing digital avancé",
      "Futurs directeurs marketing, growth hackers, experts IA marketing",
    ],
    modules: [
      { title: "Marketing stratégique et comportement consommateur à l'ère de l'IA", description: "Comprendre les mécanismes psychologiques et l'impact de l'IA sur les décisions d'achat." },
      { title: "Marketing digital avancé et stratégie e-commerce", description: "Stratégies omnicanal, e-commerce, et optimisation des tunnels de conversion par l'IA." },
      { title: "SEO / SEA avancé et automatisation", description: "Optimisation avancée pour les moteurs de recherche et campagnes publicitaires Google Ads automatisées." },
      { title: "Data marketing et web analytics (GA4, Looker Studio)", description: "Mesure, analyse et optimisation des performances web." },
      { title: "Content marketing et génération de contenu par IA", description: "Création de contenu engageant, techniques de copywriting et utilisation d'outils comme ChatGPT et Jasper." },
      { title: "CRM et automatisation marketing (HubSpot, n8n)", description: "Gestion du cycle de vie client, automatisation marketing et workflows no-code." },
      { title: "Social media marketing & influence numérique", description: "Stratégies de contenu, gestion de communautés et influence." },
      { title: "Publicité programmatique et RTB", description: "Achat média automatisé et optimisation des campagnes display." },
      { title: "Stratégies d'acquisition B2B et social selling (LinkedIn)", description: "Prospection et vente sociale sur LinkedIn." },
      { title: "Mémoire de fin d'études / Projet consulting", description: "Application pratique des concepts sur un cas réel d'entreprise." },
    ],
    certifications: [
      { name: "Google Advanced Data Analytics", provider: "Google", level: "Avancé" },
      { name: "Google Ads Search & Display", provider: "Google", level: "Intermédiaire" },
      { name: "HubSpot Digital Marketing", provider: "HubSpot", level: "Intermédiaire" },
      { name: "HubSpot Marketing Automation", provider: "HubSpot", level: "Avancé" },
      { name: "SEO Essentials (AI Optimization)", provider: "SEMrush", level: "Débutant" },
      { name: "Technical SEO & AI Search Essentials", provider: "SEMrush", level: "Intermédiaire" },
      { name: "LinkedIn Marketing Strategy", provider: "LinkedIn", level: "Intermédiaire" },
      { name: "Meta Blueprint - Media Planning", provider: "Meta", level: "Intermédiaire" },
      { name: "n8n Automation Level 1", provider: "n8n", level: "Intermédiaire" },
      { name: "Generative AI Fundamentals", provider: "Databricks", level: "Débutant" },
    ],
    internationalPathways: [
      { programme: "MSc Digital Marketing & Communication", partenaire: "EM Normandie — France", details: "Spécialisation marketing digital et international" },
      { programme: "MSc Digital Marketing & Social Media", partenaire: "Sup'de Com — France", details: "L'école de tous les métiers de la communication" },
      { programme: "Master Marketing & Digital Business", partenaire: "PSB Paris — France", details: "Data marketing, e-commerce, CRM" },
      { programme: "MBA Administration des Affaires", partenaire: "UQAT — Canada", details: "Option management et transformation digitale" },
    ],
    debouches: [
      "Directeur Marketing Digital",
      "Growth Hacker Manager",
      "Traffic Manager Senior",
      "Responsable Acquisition",
      "Data Analyst Marketing",
      "Expert en IA Marketing",
      "Consultant en Stratégie Digitale",
      "E-commerce Manager",
    ],
  },
};
