export const academicPartners = [
  {
    name: "UQAT",
    pays: "Canada",
    code: "CA",
    slug: "uqat",
    logo: "/images/partenaires-academiques/uqat.webp",
    desc: "Université publique canadienne du réseau Université du Québec. 100+ programmes du Bachelor au Doctorat. Première au Canada pour le volume de recherche par étudiant de cycles supérieurs.",
  },
  {
    name: "EM Normandie",
    pays: "France",
    code: "FR",
    slug: "em-normandie",
    logo: "/images/ebs-tn/EM_Normandie-Logo.png",
    desc: "Triple accréditée EQUIS, AACSB, AMBA. 150 ans d'histoire. 5 800 apprenants sur 6 campus : Caen, Le Havre, Paris, Dubaï, Dublin et Oxford. Top 18 France (Le Figaro).",
  },
  {
    name: "PSB Paris",
    pays: "France",
    code: "FR",
    slug: "psb",
    logo: "/images/partenaires-academiques/psb.webp",
    desc: "Paris School of Business — triple accréditée EQUIS, AACSB, AMBA. Top 3 post-bac à Paris, 4 000+ étudiants, 20 000+ alumni. Campus moderne au cœur du 5e arrondissement.",
  },
  {
    name: "IDRAC",
    pays: "France",
    code: "FR",
    slug: "idrac",
    logo: "/images/partenaires-academiques/idrac.webp",
    desc: "École de management présente sur 6 campus en France. Formations Bachelor et Master en management, marketing et commerce international. Forte orientation professionnalisante.",
  },
  {
    name: "IFAG",
    pays: "France",
    code: "FR",
    slug: "ifag",
    logo: "/images/partenaires-academiques/ifag.webp",
    desc: "Institut de Formation aux Affaires et à la Gestion, fondé en 1968. Membre du Groupe FIGS Education. Forme des managers opérationnels pour des fonctions de direction.",
  },
  {
    name: "IGEFI",
    pays: "France",
    code: "FR",
    slug: "igefi",
    logo: "/images/partenaires-academiques/igefi.webp",
    desc: "École des métiers de la finance d'entreprise et de l'expertise comptable. Spécialisée en finance, comptabilité et contrôle de gestion. Diplômés directement opérationnels.",
  },
  {
    name: "Éklore",
    pays: "France",
    code: "FR",
    slug: "eklore",
    logo: "/images/partenaires-academiques/eklore.webp",
    desc: "Grande École de commerce accréditée EFMD, membre CGE. Diplômes Bac à Bac+5 en management, gestion et marketing sportif. 3 campus, 2 600+ étudiants.",
  },
  {
    name: "Epitech",
    pays: "France",
    code: "FR",
    slug: "epitech",
    logo: "/images/partenaires-academiques/epitech.webp",
    desc: "L'école de référence en informatique et nouvelles technologies depuis 1999. 15 campus en France, 5 à l'international. Forme les experts tech qui innovent.",
  },
  {
    name: "EPSI",
    pays: "France",
    code: "FR",
    slug: "epsi",
    logo: "/images/partenaires-academiques/epsi.webp",
    desc: "École d'ingénierie informatique Bac+2 à Bac+5. Spécialisations : développement, cybersécurité, IA, gestion de projets IT. Pédagogie pratique, insertion rapide.",
  },
  {
    name: "Excelia",
    pays: "France",
    code: "FR",
    slug: "excelia",
    logo: "/images/partenaires-academiques/excelia.webp",
    desc: "Grande école de commerce accréditée AACSB et EPAS. Implantée à La Rochelle et Tours. Programmes en management, tourisme, digital et supply chain. Forte dimension RSE.",
  },
  {
    name: "FIGS Education",
    pays: "France",
    code: "FR",
    slug: "figs",
    logo: "/images/partenaires-academiques/figs (2).webp",
    desc: "Groupe d'enseignement supérieur regroupant IFAG, Éklore et d'autres établissements. 50+ ans d'expérience. Couvre management, informatique, communication et finance.",
  },
  {
    name: "Link University",
    pays: "Italie",
    code: "IT",
    slug: "link-university",
    logo: "/images/partenaires-academiques/udl.webp",
    desc: "Université privée italienne reconnue par le MIUR, implantée à Rome. Programmes en management, droit, communication et technologies. Accès à l'Europe du Sud dès la L1.",
  },
  {
    name: "Sup'de Com",
    pays: "France",
    code: "FR",
    slug: "supdecom",
    logo: "/images/partenaires-academiques/supdecom.webp",
    desc: "L'école des métiers de la communication : marketing, relations publiques, médias digitaux. Pédagogie pratique, partenariats avec agences et marques.",
  },
  {
    name: "GUtech",
    pays: "Oman",
    code: "OM",
    slug: "gutech",
    logo: "/images/partenaires-academiques/gutech.webp",
    desc: "German University of Technology in Oman, fondée avec RWTH Aachen. Programmes en anglais : informatique, ingénierie, architecture et management.",
  },
  {
    name: "RedSup",
    pays: "France",
    code: "FR",
    slug: "redsup",
    logo: "/images/partenaires-academiques/redsup.webp",
    desc: "Réseau d'enseignement supérieur accompagnant les étudiants internationaux vers les grandes écoles et universités partenaires en France.",
  },
  {
    name: "Audencia",
    pays: "France",
    code: "FR",
    slug: "audencia",
    logo: "/images/partenaires-academiques/logo-audencia.png",
    desc: "Triple accréditée EQUIS, AACSB, AMBA. Membre de la Conférence des Grandes Écoles. Classée parmi les 11 meilleures écoles de commerce françaises (Le Figaro). 11 campus dans le monde, 180 professeurs permanents.",
  },
];
